# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/dmitry/monitor/monitor_ws/monitor/backend/dsdl_messages/public_regulated_data_types/reg/udral/physics/kinematics/translation/Velocity1VarTs.0.1.dsdl
#
# Generated at:  2025-11-14 17:37:06.129151 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.kinematics.translation.Velocity1VarTs
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.si.sample.velocity

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Velocity1VarTs_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value:          None | uavcan.si.sample.velocity.Scalar_1_0 = None,
                 error_variance: None | int | float | _np_.float16 = None) -> None:
        """
        reg.udral.physics.kinematics.translation.Velocity1VarTs.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value:          uavcan.si.sample.velocity.Scalar.1.0 value
        :param error_variance: saturated float16 error_variance
        """
        self._value:          uavcan.si.sample.velocity.Scalar_1_0
        self._error_variance: float

        if value is None:
            self.value = uavcan.si.sample.velocity.Scalar_1_0()
        elif isinstance(value, uavcan.si.sample.velocity.Scalar_1_0):
            self.value = value
        else:
            raise ValueError(f'value: expected uavcan.si.sample.velocity.Scalar_1_0 '
                             f'got {type(value).__name__}')

        self.error_variance = error_variance if error_variance is not None else 0.0  # type: ignore

    @property
    def value(self) -> uavcan.si.sample.velocity.Scalar_1_0:
        """
        uavcan.si.sample.velocity.Scalar.1.0 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: uavcan.si.sample.velocity.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.sample.velocity.Scalar_1_0):
            self._value = x
        else:
            raise ValueError(f'value: expected uavcan.si.sample.velocity.Scalar_1_0 got {type(x).__name__}')

    @property
    def error_variance(self) -> float:
        """
        saturated float16 error_variance
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._error_variance

    @error_variance.setter
    def error_variance(self, x: int | float | _np_.float16) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -65504.0 <= x <= 65504.0
        if in_range or not _np_.isfinite(x):
            self._error_variance = x
        else:
            raise ValueError(f'error_variance: value {x} is not in [-65504, 65504]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.value._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        if _np_.isfinite(self.error_variance):
            if self.error_variance > 65504.0:
                _ser_.add_aligned_f16(65504.0)
            elif self.error_variance < -65504.0:
                _ser_.add_aligned_f16(-65504.0)
            else:
                _ser_.add_aligned_f16(self.error_variance)
        else:
            _ser_.add_aligned_f16(self.error_variance)
        _ser_.pad_to_alignment(8)
        assert 104 <= (_ser_.current_bit_length - _base_offset_) <= 104, \
            'Bad serialization of reg.udral.physics.kinematics.translation.Velocity1VarTs.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Velocity1VarTs_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.sample.velocity.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "error_variance"
        _f1_ = _des_.fetch_aligned_f16()
        self = Velocity1VarTs_0_1(
            value=_f0_,
            error_variance=_f1_)
        _des_.pad_to_alignment(8)
        assert 104 <= (_des_.consumed_bit_length - _base_offset_) <= 104, \
            'Bad deserialization of reg.udral.physics.kinematics.translation.Velocity1VarTs.0.1'
        assert isinstance(self, Velocity1VarTs_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
            'error_variance=%s' % self.error_variance,
        ])
        return f'reg.udral.physics.kinematics.translation.Velocity1VarTs.0.1({_o_0_})'

    _EXTENT_BYTES_ = 13

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8!e|$10{@*@-ES4g6~6}jbpc~A-!#c2p<t(Y@io5YLYk&2EecvN6dU5U3ftM;v1jc4xXjF6`ywR`53N92sVlLS@+ag^$e$3Y'
        'PkqZ<)mEy~N`22;d(Q6cz1I$=YAxBnvpciroSE~RbI$m)1AhpQ){39>jds^peqcF@NkIeggt`H<94`*ru@ai)>EUH96Hh0St#sQg'
        'f055T%|FSf(_tr~A&g&@Y~4zHNdv3RyGnS<+7uBBsYX#t8mR!}II<qHAohgrHXc&BqVjai=`g8aB<Hns^r4Yo<aW&-`d$7sPY*g&'
        'Ybo4BGnIb~HuvzhH!DwvZweOpeJ|^dPc?Nky3Y5NFZpmv658=-WGP`O8n!`6$2ey#do-Xj=c9bw9<pob2tNeI`K0-JYCzAMMvoRD'
        'vzEJ&$7LLeC(K`g7fOTbS1H<SJ#8sMp+yJQGxZ=+Vm)I1tw^(VCU?f*pyLYd1T0$DJhxl0T8}F2gs~5+J)fSuS1H2JtQ#<P2Zvyb'
        'hkl#i&(q@$_!#+A`h$v|CoU}QU?@BpE9S+KpQi^LKlbv~f9|W*RyZS361q&1c#RCqQbcpA38x)K+Egj#6D1;#5fz7wPzfd^m0c3T'
        'W2A|QV16-ETXj@w-h<Luigg&C78bKE6|-=IiAxomAwm(KtpUY+(q?j&w%dX5N`?_s<0Vp}p57;DDN(Erfg&y=l08l!Ht_kHjKjWm'
        ')eB#tjD+AAlb48MteE7*pjWkFp(0v`x3VK(ZG|hMuwI8%fO8!hBn-XOF^O0Qw+a5N1@TttUvIp*I15`swuBFUGLM3f*XwmcX36}c'
        '=Hkwsh3V9d6HVslTTRksRH{p4iwlqA5D+*5>XHx0;zFTw;9KxJ0q#h$6(@lYhQI<LNfa@UDMh6Sx}^(11R}KRc?;VHpMkd+ktSHx'
        'JWdqOD$K*MpMVNN!5S!L+XD70(!gWlNuh+Y%EjCWfD6K#z45^knT}#jZvJ$J6nUW?OR(or38YBcxL;R^+l9l97TdHN#I%Sp1PW4('
        'RXDy<g^Gme{yI!noCX0#80oeiu-RgIX=07_H!5WCqU5OV#Q{ihQ6nvI4<wF85EufRsH_|g!bCcDBaZNx=-#=56mY>vGj@x=!!Ox2'
        'JWu>`d2~h}EZIwUKU&IpBfaoTCga_v3%)_za5pxicq_8<bi^qf%G1}Xq`<b@KsZc_J5s{f{eqt~sQlsYrQ@(<58q;1y=i0^Plx7m'
        '^h~*l%hIWVeCoK}GJ)eN=J;FuUEWL}q4*4p!f|4L{yd#<*2FgR9SoEs{Cp`r>Zmx89)p2^Ic*B*A{|8tgqx@1_n>HO-@~^rAUzFT'
        'hQz^RtP&$WxG%dfIfN6YW0|LQBRN|t=PT)`OTA5ox#ln~->Jfzr{~&<3rF06LX!mOSwE-4=t!A@!4mFjp1%IlG;B4jIScjX8WZ1?'
        '!>I!IF;O_?DCf^1Tz_0DQv+HcXaRWznIe{uH!vK?a5(-Hj<(*4<>qX0cGQ5)BD#f9;FRV&&LSv?gQUzBMY8DIfd?+uIh;n=|2TwH'
        '=o`bxY&Ql?kjJWgU7Xeq%!%c!YBNu)iGdRVrDT%<rzVRKm(@H1&&w*hd&f?^yl}DfR1siD$Bv9+UFcG63OmK`P4l1g`+S+N@CWew'
        'kblHi`7esCJ>a+jgyllT;(lR)jn=!L^YqY9guY!oFSFheOZPi*J5R}8N>n#=W8eft@(v4Qld|tZuAs=RUV$8OJPyez=W%-E9`!ME'
        'e`gZcIJ%SsQ1-jKNBMid&!_EHrd()O+NFlv9!p$UXDA{px**VP6h^V|0z*-$J%r!YGJBuF{fPTA`+#{KMjXoQ5%Yf3ydN_-Zr;}s'
        'M>6}MnSTgzEVB<I9?0woGye$U!OWgC<3|yPGy9m)Glh68vyUTAX7&lhiOfEUcqp?^A=WedwE6ywv3u6oIcM~I&)9nn@myxVj(9e+'
        '-#|Q**#z-)X1|GeDzo20Jek>VBc90Y^N7bY`}>GfnSH_dbrJDsW=|XcW)P2L_B+PUA0Qsi>`TVqS+ict_<b31JhSJF{|&^^%$_&v'
        'xMKEW!K|l=xIeQO&AP6d{cV}`T`S{mUpM%!!5<nlys&>{@O^_nHu#~zRfF8%w!voxKR5V=!7mMdW$<f*-x&P1#5-d{MmSvw)0NPw'
        'gbyoWwGwzGY*)gwO8C4IzNmyRE8(k3__`9lsf2HhkU;MV^$MyS79R7?#j*qSa9sDh;YM1+vf6K^&!^)zq0s9coh{T=0(JE|zx)go'
        'hjbk(MS@N3&(e!m7Ut$#^H&xY7q7IM^Q~6%TC35xI=9ehU0G-?G#iW8=9>!(W!)>xPlgN{83#_bW7=8X;D3dJ$Zw&kzwopCU;J+g'
        'x1aOdOZ?6r$t~Td1XP>yx&T$Sx-jJFk@Cv0v&8U6&(RA1^^T0Yr;ZVG?O>d}BDr$TH_NmX@yEUF)#*u(2Qu0TXj`z3M=wo{>3EqL'
        'p#Wk{c&RqYKedNo2Y&-S&S&uZ^pm_wPm2F}2}Yg_<VXTJk|~_M3bR*VGW%1^n|qHNvJ97PP#K~Dp8UPXj7h@`{tuwT@M5z$x6lvv'
        '1d|eaiVifkG{REVNRRz$x?sTNGWs)*=0DD>=x>}Js@3?>4Fa%n2L8O72I+oiLg1EJ+;_3_DQ~>c%=GWPaBm&B_2%iRo%dcKNn;mH'
        '(m&mXuc;&zAIip|-$&4*jjz^Z)$h94v#_e66y^N@nuGGD4js5k+@h<1M*6>9bqn6sZ$hI1O-&rl_RK>20fK;4vBDv|e)PR4+7fJL'
        'CEX&+x5_5Q7tp-upljtN@&AwQn%MPkg1t_}#@i6B|LIU{jKCMg!^SvBd(r;iJ=*t(`dzk9_Snv067Nr{NWSwma@+b3Hw@jYco6^q'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
