# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-11-14 17:37:06.165759 UTC
# Namespace:     reg.udral.service.actuator.servo

from reg.udral.service.actuator.servo.__0_1 import __0_1 as __0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
__0 = __0_1
