# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/dmitry/monitor/monitor_ws/monitor/backend/dsdl_messages/public_regulated_data_types/uavcan/pnp/cluster/Entry.1.0.dsdl
#
# Generated at:  2025-11-14 17:37:07.892070 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.pnp.cluster.Entry
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.node

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Entry_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 term:      None | int | _np_.uint32 = None,
                 unique_id: None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray  = None,
                 node_id:   None | uavcan.node.ID_1_0 = None) -> None:
        """
        uavcan.pnp.cluster.Entry.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param term:      saturated uint32 term
        :param unique_id: saturated uint8[16] unique_id
        :param node_id:   uavcan.node.ID.1.0 node_id
        """
        self._term:      int
        self._unique_id: _NDArray_[_np_.uint8]
        self._node_id:   uavcan.node.ID_1_0

        self.term = term if term is not None else 0  # type: ignore

        if unique_id is None:
            self.unique_id = _np_.zeros(16, _np_.uint8)
        else:
            if isinstance(unique_id, (bytes, bytearray)) and len(unique_id) == 16:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._unique_id = _np_.frombuffer(unique_id, _np_.uint8)  # type: ignore
            elif isinstance(unique_id, _np_.ndarray) and unique_id.dtype == _np_.uint8 and unique_id.ndim == 1 and unique_id.size == 16:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._unique_id = unique_id
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                unique_id = _np_.array(unique_id, _np_.uint8).flatten()
                if not unique_id.size == 16:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'unique_id: invalid array length: not {unique_id.size} == 16')
                self._unique_id = unique_id
            assert isinstance(self._unique_id, _np_.ndarray)
            assert self._unique_id.dtype == _np_.uint8  # type: ignore
            assert self._unique_id.ndim == 1
            assert len(self._unique_id) == 16

        if node_id is None:
            self.node_id = uavcan.node.ID_1_0()
        elif isinstance(node_id, uavcan.node.ID_1_0):
            self.node_id = node_id
        else:
            raise ValueError(f'node_id: expected uavcan.node.ID_1_0 '
                             f'got {type(node_id).__name__}')

    @property
    def term(self) -> int:
        """
        saturated uint32 term
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._term

    @term.setter
    def term(self, x: int | _np_.uint32) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 4294967295:
            self._term = x
        else:
            raise ValueError(f'term: value {x} is not in [0, 4294967295]')

    @property
    def unique_id(self) -> _NDArray_[_np_.uint8]:
        """
        saturated uint8[16] unique_id
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._unique_id

    @unique_id.setter
    def unique_id(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray ) -> None:
        if isinstance(x, (bytes, bytearray)) and len(x) == 16:
            # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
            # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
            self._unique_id = _np_.frombuffer(x, _np_.uint8)  # type: ignore
        elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size == 16:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._unique_id = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint8).flatten()
            if not x.size == 16:  # Length cannot be checked before casting and flattening
                raise ValueError(f'unique_id: invalid array length: not {x.size} == 16')
            self._unique_id = x
        assert isinstance(self._unique_id, _np_.ndarray)
        assert self._unique_id.dtype == _np_.uint8  # type: ignore
        assert self._unique_id.ndim == 1
        assert len(self._unique_id) == 16

    @property
    def node_id(self) -> uavcan.node.ID_1_0:
        """
        uavcan.node.ID.1.0 node_id
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._node_id

    @node_id.setter
    def node_id(self, x: uavcan.node.ID_1_0) -> None:
        if isinstance(x, uavcan.node.ID_1_0):
            self._node_id = x
        else:
            raise ValueError(f'node_id: expected uavcan.node.ID_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_u32(max(min(self.term, 4294967295), 0))
        assert len(self.unique_id) == 16, 'self.unique_id: saturated uint8[16]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.unique_id)
        _ser_.pad_to_alignment(8)
        self.node_id._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 176 <= (_ser_.current_bit_length - _base_offset_) <= 176, \
            'Bad serialization of uavcan.pnp.cluster.Entry.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Entry_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "term"
        _f0_ = _des_.fetch_aligned_u32()
        # Temporary _f1_ holds the value of "unique_id"
        _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, 16)
        assert len(_f1_) == 16, 'saturated uint8[16]'
        # Temporary _f2_ holds the value of "node_id"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.node.ID_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Entry_1_0(
            term=_f0_,
            unique_id=_f1_,
            node_id=_f2_)
        _des_.pad_to_alignment(8)
        assert 176 <= (_des_.consumed_bit_length - _base_offset_) <= 176, \
            'Bad deserialization of uavcan.pnp.cluster.Entry.1.0'
        assert isinstance(self, Entry_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'term=%s' % self.term,
            'unique_id=%s' % _np_.array2string(self.unique_id, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            'node_id=%s' % self.node_id,
        ])
        return f'uavcan.pnp.cluster.Entry.1.0({_o_0_})'

    _EXTENT_BYTES_ = 22

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8!)O<20{`up%a0Vt9mi*udF||jf?Z&F{|uNc#2y2|_6FxgObDn0Ug3wVNT}5_Q@hnL(>>|#fn7_M@F5XIEu|&el8=3gP)@BJ'
        'B9ugO66e7s@+AjH%E>4H2|ngmGv8vD4jVZ+gS7h9Om|mT)%54{t>#YU!%q*CM*rf&gY|CM?X~Ps2Cma{-*ehM*|Ix+f8d91B-422'
        '%_talqG2H4S|7;tetP1A^!;=(uG*f{=i>`Q=T^t@S_5y;>hy+TB!kuuyeL>t<A!}p2BGVFsVc?wchJ6{T4k&Bv-E>Bp0b@N3f%TE'
        'l3{wCJKbV9kIzcu>P1)fx*Nl2+Fd7d>`0GotIG$0+jk@P7N0Tqwimjqp6p)sBDpGqC+9R}x82C@NpCe$sYTp*#|b05?{{UY=HuPV'
        'rXzh>>vcYMMIYiBm42FDOXGPvj2y4)1l`RY-5s`7HLmc&^wYRvcl}NpFJ6-?GN8z(NJ+ZptVA?$2K>#6ACO!d^c>HLc(qz7Uo6JM'
        'Q*-hDE!HOp9A5AFi|(52{%Ca9^ZKhNXE$TZp6p968n2exjc)f^4Yf}lQipk<@gz@q;B?$*J+%anw%rTU__(?4#;kY*QSoycPk-Ny'
        '#`k}dKjO~uHrpShF>TdJxZZF3J(pKy?uzXDJSjc%H+VIi$PYHgU$Z;P<=<Yt9Phj)2QqS>e%^$AlgF;k@p;>?4tqT(STCN$ecf_;'
        'Lz(^}U9=iW*yfp6?7r)z)*an&)^ww;fB9k0(Y;z_eQGJOCQ!HOI+0ive6H%cEwO6&zK+_!@kxAcj&EsA=~_>$X?&j1bt<uDao%=('
        'FL3=1T_+Q3CyvkQI-6MYIByre->vJ;#M-0lOkyqI_+E@}pRNmuwO`ly#5$m>NUVdpPAAqOoPSu?N@5Z2|D3J|6YGes`x5J@u6q*e'
        '82Wi$*Byy<9OL>L=Cg?YPUu=qtdkh$*L6LaSTE?hm{>3BdOWdOx*kicmvlXnSf_NQ#5%3(p~O0)>w(1j2F7s~^Lbg<-HG)I#`7xH'
        'VF~m5CdPFR^L$O$W@3E{<NLO*wZ!@k=KWoa^Lv>8C0&;i>s^dj;l69Q{;sZf66+(>2dEEGAEADR`UUEj<9el0Mq|M=7ENQxG%lIO'
        'yQZN`W6d<~n#M<_@xU}5n#Lp3_{=oEFpV$K7_$7>Lyk9cHoj|XP}pUYL(l!mP}(lT_*~q2d-UnW%NNLBVV}7nIlZ3W8Dabyy(a^o'
        '+!Y#nH$DG$!Dwm%t!g}rAn{nKt;-iuRacWHDb)1!bkju}<`R$1#XVHVO!JURd=n?0+Y~Q$dwm>O@2BcF>enH=zAFcT<Wb6QdM}=}'
        'SF}9sfgePAURUECcIXd-j^qP9X%8GWd0f|}=eE;$a+&jSZCQVNpPf^FiPf%r9f-9qXM~Qwdf)e4EuFZDmVG-+)hBVi?R0KRugl@8'
        'jcE5}7&@yQf$aBTn@wm3a+STqBil$fK3W^E5Z_6!5y$7{3$4?wQ!U*|8tDL<vy~I_SOaZ&&WKxXN2d39K|a19S6ol>FGKoT{;gWg'
        'w>Wv&bZ&pxCtf+XOQZE8{{47qczoOm`Q9j@hWsh$t-IbTMFBq)dYP!_taI2m-_civ)bnraL{pAOr_U@AkAWY9+s=B3&ULc!bFp!K'
        '*lIqJg5f}R+!c5H+>B1|``n4^t@y1p7NehUyfg85WaAA(aY-il!IANv(a&W^z8&~}G`cY4P~%7A<3;rc^+)w5^@;j3|NTY%RsBsp'
        '(rc$$>h$QbQfJkxc)msvvg~xbJn#R=89sV`e8GjWV!}4>cn0IMQ>(#`<VAiyf5?BAwhWMRAwbFqkjfSTQb&N)5Fk|qNCg41tq>sP'
        'LVySah(Le{1c*R@2n2{gfCvPLK!6AYh(LgdLVySah(Le{1c*R@2n2{gfCvPLK!6AYh(Le{1c*R@2n2{gfCvPLK!6AYh(Le{1c*R@'
        '2n2{gfCvPLK!6AYh(LgdLVySah(Le{1c*R@2n2{gfCvPLK!6AYh(Le{1c*R@2n2{gfCvPLK!6AYh(Le{1c)#JB20h?6ClC_h%f;n'
        'On?XzAi@NQFaaV=fCv*H!UTvg0U}I*2ooT}1c*q6>X&Gk)TnDjks151jxF?*#LxjD)k94fsU7NpI(p-Lxl~fW8miykQ@^{ae!m69'
        '@iu-3VeR5AB#mcB?;%erQvF@)@aJ!Ml9s(?Bg0L%Cpo%^?Z~6j;?+KMcz4di8x0oQ^^Wg_(hG-r=&OF<MylVU<(_mxNx^2Vjrur0'
        '&_dPYaaonxZCx2TZZB-5>eDAgR-8n2{4yogKmKQV{p)dSv(R?E?t41*yr*un^$URBWpjdP!T$H&Zv2>kn9+wD*SWRT`I|LKtV#8`'
        'RUX-q*p4)|qp{pq+GbA_w%HZfu?jm*z>dwr_PPc;R$#}8f*rTRj<c}i4D2`!J5IrlP1td=u)VIsjy2e^3OiO{$8E6V1ngKYY_AD+'
        'B-oK)M}i#*b|l!5U`K)-33epdkzhxH9SL?M*pUj`Yl0mKb|l!5U`K)-33epdkzhxH9SL?M*pXmIf*lEVB-oK)M}i#*b|l!5U`K)-'
        '33epdkzhxH9SL?M*pZAK$=H#M9m&{{j2+3?k&GS5*pZAK$=H#M9m&{{j2+3?k&GS5*pZAKxzScjGSo0+3`6!6U?^@GN`);$t*})n'
        '0ft&(t55+9HNem;z)&x26&iq{1Q=!jLk%$OE^HN=fT02y_5y}^z_1-KGyy}k0K);mumBk53tNS0z|a5;6~Ise49^3GBY@#BU^oC6'
        '_5z08fMKq%RhR(`O~6nG3>Cmo1`KBb!x_ME3NW+)!wZ1nBw$zs495Y(F~D%70E5{oTmlSBfMF3ZEC7ZEV8{SN1{gBHkO77aFk}XX'
        '%)pQt7%~GxW?;w+44Hu;GcaTZhRnc_85lAHLuO#e3=ElpAu}*!28K+-@HsZl&uDl?!!sKGIgW;$VaWfFeNwrwPbwGoN#-rGRM;og'
        '0Yd{YOch|L74}Kh!dqkmFq8np_QF1?3>fAC!z^HE0EP*`un#coD!fHb0fri2C>Qog2LQtYV3;qwMNR{T24JWFh7w>n0T_-0hNFdj'
        '(m}wm4>0Tj4D*0t2Vj^53{!xi0T`-)VFECm0}M-m;T6De7BHLv45teFq!M7b1Q?b8!y;f<01OSlkOPJsFyw$C2MoD^AvZAO28P_g'
        'kQ*3s14C|L$PEm+fgv|A<OYV^z>pglasxwdV8{&&xq%_y91YKCct*pRhD}e0{y&D+zX2ayG&9;9000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
