# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/dmitry/monitor/monitor_ws/monitor/backend/dsdl_messages/public_regulated_data_types/uavcan/pnp/cluster/391.RequestVote.1.0.dsdl
#
# Generated at:  2025-11-14 17:37:07.894421 UTC
# Is deprecated: no
# Fixed port ID: 391
# Full name:     uavcan.pnp.cluster.RequestVote
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class RequestVote_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     term:           None | int | _np_.uint32 = None,
                     last_log_term:  None | int | _np_.uint32 = None,
                     last_log_index: None | int | _np_.uint16 = None) -> None:
            """
            uavcan.pnp.cluster.RequestVote.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param term:           saturated uint32 term
            :param last_log_term:  saturated uint32 last_log_term
            :param last_log_index: saturated uint16 last_log_index
            """
            self._term:           int
            self._last_log_term:  int
            self._last_log_index: int

            self.term = term if term is not None else 0  # type: ignore

            self.last_log_term = last_log_term if last_log_term is not None else 0  # type: ignore

            self.last_log_index = last_log_index if last_log_index is not None else 0  # type: ignore

        @property
        def term(self) -> int:
            """
            saturated uint32 term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._term

        @term.setter
        def term(self, x: int | _np_.uint32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._term = x
            else:
                raise ValueError(f'term: value {x} is not in [0, 4294967295]')

        @property
        def last_log_term(self) -> int:
            """
            saturated uint32 last_log_term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._last_log_term

        @last_log_term.setter
        def last_log_term(self, x: int | _np_.uint32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._last_log_term = x
            else:
                raise ValueError(f'last_log_term: value {x} is not in [0, 4294967295]')

        @property
        def last_log_index(self) -> int:
            """
            saturated uint16 last_log_index
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._last_log_index

        @last_log_index.setter
        def last_log_index(self, x: int | _np_.uint16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._last_log_index = x
            else:
                raise ValueError(f'last_log_index: value {x} is not in [0, 65535]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u32(max(min(self.term, 4294967295), 0))
            _ser_.add_aligned_u32(max(min(self.last_log_term, 4294967295), 0))
            _ser_.add_aligned_u16(max(min(self.last_log_index, 65535), 0))
            _ser_.pad_to_alignment(8)
            assert 80 <= (_ser_.current_bit_length - _base_offset_) <= 80, \
                'Bad serialization of uavcan.pnp.cluster.RequestVote.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> RequestVote_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "term"
            _f0_ = _des_.fetch_aligned_u32()
            # Temporary _f1_ holds the value of "last_log_term"
            _f1_ = _des_.fetch_aligned_u32()
            # Temporary _f2_ holds the value of "last_log_index"
            _f2_ = _des_.fetch_aligned_u16()
            self = RequestVote_1_0.Request(
                term=_f0_,
                last_log_term=_f1_,
                last_log_index=_f2_)
            _des_.pad_to_alignment(8)
            assert 80 <= (_des_.consumed_bit_length - _base_offset_) <= 80, \
                'Bad deserialization of uavcan.pnp.cluster.RequestVote.Request.1.0'
            assert isinstance(self, RequestVote_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'term=%s' % self.term,
                'last_log_term=%s' % self.last_log_term,
                'last_log_index=%s' % self.last_log_index,
            ])
            return f'uavcan.pnp.cluster.RequestVote.Request.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 391
        _EXTENT_BYTES_ = 48

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8!)O<20{@*=`)?dI5Wc8sk|s?_6q*)QqKklVNOWmb0peBKrma+tgwypQBnp;ycXDHO*IsOI$RQ9-3soywB2vun{Hct0^SC^Y'
            'A2{i>v$p5+%s1c6J{|vieyUaf+~snRnJkZ)0WEkge&I<DF-uiZDkCg-H+vg$QIMHE7?j|5{QFz}H{W&>Oh^gZW6RCnx4KGgrQz_A'
            '(@gS$AeJh=k#ZTAvW(NbG8S~)gP$re_K~u%XL~orHb5JpWI&yKv}^D9&RD1Q!f$yu!??9tB$Wl@f1oQy#J_*ayVG|C<k>+`(=6kb'
            'GaDiu<zDKLvDly!3lF6ceF@n;X`v7LaE3E15tij3`xbpCBJh+O%L<i&$2Z(!cMmAI#VfS88n!5-)}OxT-RsO)E;FvPVW5{)g41rC'
            'XezuLXPHX9Yk68c-&~6q@zSpKW+%eS_%^=N_{`?v`dsx{?TkzK-Uzq3VYhSpZbD|TNq(-~gLTl6Rgp!AdVJkRB`;}ZUFirm%bZJY'
            'sX8&m1#V%eE-V=|bq^Q4i;MUHws9G+RK!*WrG}J~nEWeuj;)JL$XKbgWg_!yZk`!c=@e)q2Uc?8!cB%pE)ws~bV-t%-LSet+>d=o'
            '<e&-yo5+Y|J)pydlENzO-Sn=-el{MjyUB#7Pe5j*=TLA~fHAyJB663?D#=C4H1w-HM0TJL+MQ^m>)k05FX8XX*Sm|?K3zT};^p{i'
            '9H6}og<W9C4P~G~+90kCk%E6oyy62CCJN{gJvou8ZKT!@SWcBRAWcP^d0%N^v52E?4%|Sbhig(}+$>AV>W(Dx!PK?Mz;cnB*t@y9'
            '3{5Xfilgb6kr~YlWkc(GO$qKoT?u9t(@NPI)Rdg^!Oz<GIevj(;&uFr{x|R@-olldfN_@O#NX0hgB{45=&(oMy*qnL*l+6h`}Dfo'
            'VD1!C6k{|B#0-i=QSpfHRVWm-Z;<4-BvT$lFf^-D6f^|zv3sq{vrNeTu|vr5$9?OuJHMi25UM;8(w%7#sl0*IA<y&#G*Mfak2*<F'
            'tyOu>_2Ae&6KsR$75Kk=yAy4jghpi9BtS#4N{Hq{$S`@x;G4mi4AX~{9K5F)bt;$j6kVfE|FsF^_dPT)2|nxGz~}V;gEn4-Lt6p('
            '`0}vt+`ey@4t0lpr>f)2CJ9ppXYee};e23Wkw(H5z-vcG1b*}iKVHL6Mkot!;~l&k^o94Rnec1u{4Ysk@4uuwNvu)ftzUgQ<`!vY'
            'HQztY5O_w9`qOb_0>9N63j@6ws1NbGhOF;Lh~Q`)4k_<KkIO#vpad&M$@xiB?W^Q4j5W1gQ~hiWpHu9C|ISocZ*7~p5OvMM=07KF'
            '2G{ssOS9<j90&ja'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     term:         None | int | _np_.uint32 = None,
                     vote_granted: None | bool = None) -> None:
            """
            uavcan.pnp.cluster.RequestVote.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param term:         saturated uint32 term
            :param vote_granted: saturated bool vote_granted
            """
            self._term:         int
            self._vote_granted: bool

            self.term = term if term is not None else 0  # type: ignore

            self.vote_granted = vote_granted if vote_granted is not None else False

        @property
        def term(self) -> int:
            """
            saturated uint32 term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._term

        @term.setter
        def term(self, x: int | _np_.uint32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._term = x
            else:
                raise ValueError(f'term: value {x} is not in [0, 4294967295]')

        @property
        def vote_granted(self) -> bool:
            """
            saturated bool vote_granted
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._vote_granted

        @vote_granted.setter
        def vote_granted(self, x: bool) -> None:
            self._vote_granted = bool(x)  # Cast to bool implements saturation

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u32(max(min(self.term, 4294967295), 0))
            _ser_.add_unaligned_bit(self.vote_granted)
            _ser_.pad_to_alignment(8)
            assert 40 <= (_ser_.current_bit_length - _base_offset_) <= 40, \
                'Bad serialization of uavcan.pnp.cluster.RequestVote.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> RequestVote_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f3_ holds the value of "term"
            _f3_ = _des_.fetch_aligned_u32()
            # Temporary _f4_ holds the value of "vote_granted"
            _f4_ = _des_.fetch_unaligned_bit()
            self = RequestVote_1_0.Response(
                term=_f3_,
                vote_granted=_f4_)
            _des_.pad_to_alignment(8)
            assert 40 <= (_des_.consumed_bit_length - _base_offset_) <= 40, \
                'Bad deserialization of uavcan.pnp.cluster.RequestVote.Response.1.0'
            assert isinstance(self, RequestVote_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'term=%s' % self.term,
                'vote_granted=%s' % self.vote_granted,
            ])
            return f'uavcan.pnp.cluster.RequestVote.Response.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 391
        _EXTENT_BYTES_ = 48

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8!)O<20{@*=-)|d55VqAcPUDoegr-H6s4GfpUXGL^K`B2IRD?`Sa7(F>s@2}z#Ix$%?y<Y)#z;u*1E`T!B2t!j{#0h~Qs>gv'
            'JYeZ`do#P=&V2LD`02vmZ+2SM&s{C1sY$bl8PI}f;x`^=5V1t%g)+i|cW1wWOysmo?@tTxhyML%{&(MZi%duf+GER|y=Qfq*iysE'
            'EvK2}IYHbg`6S^oDr6BQS!pcjXav8OVC(~Bf!3x_($LN&HUVvfk^#2!;Anm52kk-YPyfujF5}i}5tkN>e?)i8Nnp0iyVG|CWa)8K'
            '%Pi%VGaEvkcf8OcWig>0t3OF2#uC!+q=hl)lPPvtEG)}FjxG8@kH8adEX!329^ZCrJ1>C3v1p5Y+rdQ{wf^uU@7`j@a+z|SHi4d('
            'F)q6W;wkrTfu$<(uI0&ivAz~B6Lxn~sSLP05fHvJXya9U7q9PE7%LMZn2j~3;8Tz5u0MiZ&^@bq7NIxdyS7*Gf-JjA_h7Hcxa5{d'
            'kLWsZs|~tYJgw^)u6YmFFv5OG1f)=CNO-{CcW<y=u?HzDl(tNye&{YRqe`6sIWk}cr}SJWyfP7ccV>rVwzm_kheT)l1Iiaw5Y1vr'
            '#OWz*&Xp8aY44VgR_uxKc*k{Oo;(Jbl14)fSq{eVG3mlxDatq#3DYnxvk=*F$;rD|%h9`2BuK(PlB9Q+Z{5CmLYOzBjVM5S8)~)6'
            'kQ>TCgS0^}6On*_j_Y{Cov)aw+eVVR*5=%cx{XUn^fUc~yHqj6tYTUzTcMhQ(>?fcA3wp{_$l7O&*=FazrZi?t17Ss7H5>#`U@=|'
            'D~ZCiFMoTtvMKEM)%QL6Jd%z(#S{hEn+Ia1d8~+3;$a(dMV%64@&ieShvGEmLV|+&4IjF5J3LK=9KW&&AK@>v)kAl2OUWQ0`C3SK'
            'rbZ;%1FMabtbuWESY{d5(^pO}vI);h@PGOKpm$(mnlVKk7EP5hCh~G2L+jFl?}bGtv@hu<oL*+s6I@nfXh<EUDp1q`txafPVk`&O'
            'a6-=$a!kV}J6I}%xliW)%xvP&k=Vr*JdYPbCTrLS+-SBFez=dfhWOE(YU9_qiCdxOc()QBe*6D)hQt5TQ-_kKYFNMhwC&cY!RtQ&'
            '%@BA>uWEGSmD$AU(ZsnnXorD@*Td}k5%1SL{oJS))Fup>H)#w-IU$EjBQD1<f&#3Vr?JO%u{P*H6Km<9V!0gRgklfW50-+xbzrI*'
            'ROJfJe_rDZN27lMc{G^U9R~ma'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.pnp.cluster.RequestVote.1.0()'


    _FIXED_PORT_ID_ = 391
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8!)O<20{_ic-)~e!6y6P`yYvT?REiNTmuPTNTmci~uSB4L;@Yw)h=~aq=iWQrGjMn2GBdZfCMJ+5v~dzi7~hRP_!pS?>Vx4y'
        ';)8#YXYSo@x82=h(FdFCy>sWxIWy-w-*={WM!x@ZqLlyHqv>j_<D^bBQ=BIJOByDuP9oV(rRIh?JARd^Wgf9>t0{92-HE&ID_66V'
        'M6uf$(}oy74<$Q!fhD|+F7eitql62=RKDb@QCVa%wJq3QB4``8I-b$xh>ChD(t4C++AvjLEVj8W4cizyTP4d(X)cA2TDjgCKXi?9'
        'qjb;R#X}QnjN)Ntn07aCiy?V-S2?@)5@$)gd8jcGQ$vgNhPkK8XUvyz#q=ja^Oj)oWnoy0sjV4~laL#dFwrvL8UY56C}P)^F=97s'
        'XPO&<yjy(^ZS&rQ8I`_qi_Shnw4oxVD((%mmW6P@jv!2JXGcgZBWFtvC!Z^}g%=>`j9zR6@DkMEMBy`;`0W$fBDpiX3MYrSP4&9%'
        '@49gjvlaBSwMDkXRA6LafCY<m$pk4)ab`)XfUTqn71UsL>Ub_@r+ex`!quYgexq052%Lu3;7vG_AzCp@6^kg6$*tS{WQnh^n50q}'
        '!eh5!4-zdi6)`j<jHDE?uoeGGc<AiDCQ^5$>1Q7z_T|?R9FU%1qcNhaR&jA#3T~uwcC0fZUuXw&wi43l789|vlfK}j&9tU1B#}Lm'
        'W?{l3<b5kk{K+=?f!5K2y3X!F@?!iBeVu*wjkiy4A@S+@sk#sCj4$jo0je<r#f0(X@=9}Sh$~zJt^*%Ez&Axul?mk1Cd!c%nhBku'
        'F=<J~4Ycb)GhtM-K=sxnk8v(dF{_IL!Dl+JP0S4CiLN_4m6xH=yufo5iW!>GcuzJszadIy59gI2MiM2Z$%E>YVm|PG4bH+jI1h7h'
        '0e=_a5_|w3<^YV4FhTr|ZwPFY-Ux@;{_X6<d2T+=zpvtFM__gjk$A>nSP;G14kZ>3@t$XGiSqT7yn-~Po&-I;Dgus80H{6Cq;bqe'
        't8Wo3LDU^lduUDyPgF55q}^9U#PWJjdpu!4G?9<s_OO+Bs)Z~`s9NpYXOt|{BxCM7S8D_hbcii7EfT<{n1u*)n+xB0a6ni5pyIm^'
        'GTD2N5mYJ_c^6$krQa<M^7TeErbD>jI16j|TSvpUe$hQ2xPQ9WcdF~##6`_s-)h!BtwY~sU<wYxA(-(f9Kn`whQV9gTLiqb4(~3&'
        'dqbE7m*FF5cz(eGiV3bj^QkBepYBB63ZjOEH*Wq;+0J0kD(*i;fYBIV#m%_210QdceM2uA>Su7H0PFK1B-mbuEzCQ-NJWb+vXmJ<'
        'jLx@;YM(-f-dNQKIn?(TU=7di@o!Z9eCdJC3z65%8-EyJ^sd;G6^h%ppiY{V&dJ7LqBA;RUw-0!UW9O)1%KkrH8S|ZnziHSrNr(h'
        'wp_gET`s)WbMJ{|+?TWz75-}3?e$gg@DF$df5GG3a`5D?I9Tmsvoi??bLeTBOCQ%Z^c|o^gTeYPclCV?7ai-@cMYd&+x7kXX1O21'
        '<Nqb9KYCgGw2gy5|9jQ`(i#2w-%AqNJ-f5s2Fk38ewEJu^8K><4Xstxm1%A+3U+h0Tq@ms-an4{$5DI~#hbrh{zv6o-)&>wxn@~d'
        '{~Lnvoj%zN000'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
