# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/dmitry/monitor/monitor_ws/monitor/backend/dsdl_messages/public_regulated_data_types/uavcan/node/430.GetInfo.1.0.dsdl
#
# Generated at:  2025-11-14 17:37:07.832776 UTC
# Is deprecated: no
# Fixed port ID: 430
# Full name:     uavcan.node.GetInfo
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.node

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class GetInfo_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self) -> None:
            """
            uavcan.node.GetInfo.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            """
            pass

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            assert 0 <= (_ser_.current_bit_length - _base_offset_) <= 0, \
                'Bad serialization of uavcan.node.GetInfo.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> GetInfo_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            self = GetInfo_1_0.Request(
                    )
            _des_.pad_to_alignment(8)
            assert 0 <= (_des_.consumed_bit_length - _base_offset_) <= 0, \
                'Bad deserialization of uavcan.node.GetInfo.Request.1.0'
            assert isinstance(self, GetInfo_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
            ])
            return f'uavcan.node.GetInfo.Request.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 430
        _EXTENT_BYTES_ = 0

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8!)O<20{?ZBOK%e~5XVyyniAgPQA&C238j~%2*iaG96(i|R4w9$Ebn?6TkP74A8CSAiCz#$mO$$8G5B134aS?aLam6j%8Wh!'
            'd*(OeFWp~%&UD&eyx&ZP6IIR}Sj8*#nHLr0tTc6FobrJ2;*PhW^ufZrX#;qOYX`WGgLsx{Ueo?+;Nz0(TpI!TEASh7*W}yqDS-1B'
            'm)IDrQ%0lg#NPY4eTc(_VdpCzU_8&b_f{3bgToIPul?h*VmiBIKg9`XER@`X!0+)A+f@?~tTEOzC2%udWzGa!0&P^l8tx^=Uizz4'
            'f$`iHl{48&tA~{Q!b6N*X;S`+qE_BcDY!OTd1Ep5=N8*@C|6>y;N?fqf><P0tOn=!h|-O#O(-f=G7F<nrOcS%o-<FNXm@c&hHgr1'
            'FkXN1c>S2rqkKJ2YUpu0RV}%rq%CNlS}|57;J4Ui!ju?)zYJBCC6P?g+04%9=KbfiY<4p*f!3%+8bljmYwn42<|L<x0y5`mq09zB'
            'my+udh_!4_5~ud)OxR^MXsz@p?{E0zN;Q(zl!R#*YAT<!y~$i?5_398A@fW#x{A*;bUDT=ZP#W)q^Y9R*ug0ry*Uc9j>ZMza@#rP'
            '4YS7hR>w7*V8|N-c~dUSTXIF-rf*f=k$2_2mR^??74d#>G|PqZtO7kEAqW1XkMY6_<zKh{4!QG*j%S!@FlPS~anrgm)NE?j8>kJv'
            'l!W+g1D2<uIer(5tR%7m<<oe1iwi+SPX)<mX?K&l%I);zE-8$86##$WVA%QT3VKA%ObCZdp`dbWrE%Cv2A?FO$7&;J0@LX}gGs}6'
            '`_48);fhe?e*tmYDueO^000'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     protocol_version:            None | uavcan.node.Version_1_0 = None,
                     hardware_version:            None | uavcan.node.Version_1_0 = None,
                     software_version:            None | uavcan.node.Version_1_0 = None,
                     software_vcs_revision_id:    None | int | _np_.uint64 = None,
                     unique_id:                   None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray  = None,
                     name:                        None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None,
                     software_image_crc:          None | _NDArray_[_np_.uint64] | list[int] = None,
                     certificate_of_authenticity: None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None) -> None:
            """
            uavcan.node.GetInfo.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param protocol_version:            uavcan.node.Version.1.0 protocol_version
            :param hardware_version:            uavcan.node.Version.1.0 hardware_version
            :param software_version:            uavcan.node.Version.1.0 software_version
            :param software_vcs_revision_id:    saturated uint64 software_vcs_revision_id
            :param unique_id:                   saturated uint8[16] unique_id
            :param name:                        saturated uint8[<=50] name
            :param software_image_crc:          saturated uint64[<=1] software_image_crc
            :param certificate_of_authenticity: saturated uint8[<=222] certificate_of_authenticity
            """
            self._protocol_version:            uavcan.node.Version_1_0
            self._hardware_version:            uavcan.node.Version_1_0
            self._software_version:            uavcan.node.Version_1_0
            self._software_vcs_revision_id:    int
            self._unique_id:                   _NDArray_[_np_.uint8]
            self._name:                        _NDArray_[_np_.uint8]
            self._software_image_crc:          _NDArray_[_np_.uint64]
            self._certificate_of_authenticity: _NDArray_[_np_.uint8]

            if protocol_version is None:
                self.protocol_version = uavcan.node.Version_1_0()
            elif isinstance(protocol_version, uavcan.node.Version_1_0):
                self.protocol_version = protocol_version
            else:
                raise ValueError(f'protocol_version: expected uavcan.node.Version_1_0 '
                                 f'got {type(protocol_version).__name__}')

            if hardware_version is None:
                self.hardware_version = uavcan.node.Version_1_0()
            elif isinstance(hardware_version, uavcan.node.Version_1_0):
                self.hardware_version = hardware_version
            else:
                raise ValueError(f'hardware_version: expected uavcan.node.Version_1_0 '
                                 f'got {type(hardware_version).__name__}')

            if software_version is None:
                self.software_version = uavcan.node.Version_1_0()
            elif isinstance(software_version, uavcan.node.Version_1_0):
                self.software_version = software_version
            else:
                raise ValueError(f'software_version: expected uavcan.node.Version_1_0 '
                                 f'got {type(software_version).__name__}')

            self.software_vcs_revision_id = software_vcs_revision_id if software_vcs_revision_id is not None else 0  # type: ignore

            if unique_id is None:
                self.unique_id = _np_.zeros(16, _np_.uint8)
            else:
                if isinstance(unique_id, (bytes, bytearray)) and len(unique_id) == 16:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._unique_id = _np_.frombuffer(unique_id, _np_.uint8)  # type: ignore
                elif isinstance(unique_id, _np_.ndarray) and unique_id.dtype == _np_.uint8 and unique_id.ndim == 1 and unique_id.size == 16:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._unique_id = unique_id
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    unique_id = _np_.array(unique_id, _np_.uint8).flatten()
                    if not unique_id.size == 16:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'unique_id: invalid array length: not {unique_id.size} == 16')
                    self._unique_id = unique_id
                assert isinstance(self._unique_id, _np_.ndarray)
                assert self._unique_id.dtype == _np_.uint8  # type: ignore
                assert self._unique_id.ndim == 1
                assert len(self._unique_id) == 16

            if name is None:
                self.name = _np_.array([], _np_.uint8)
            else:
                name = name.encode() if isinstance(name, str) else name  # Implicit string encoding
                if isinstance(name, (bytes, bytearray)) and len(name) <= 50:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._name = _np_.frombuffer(name, _np_.uint8)  # type: ignore
                elif isinstance(name, _np_.ndarray) and name.dtype == _np_.uint8 and name.ndim == 1 and name.size <= 50:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._name = name
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    name = _np_.array(name, _np_.uint8).flatten()
                    if not name.size <= 50:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'name: invalid array length: not {name.size} <= 50')
                    self._name = name
                assert isinstance(self._name, _np_.ndarray)
                assert self._name.dtype == _np_.uint8  # type: ignore
                assert self._name.ndim == 1
                assert len(self._name) <= 50

            if software_image_crc is None:
                self.software_image_crc = _np_.array([], _np_.uint64)
            else:
                if isinstance(software_image_crc, _np_.ndarray) and software_image_crc.dtype == _np_.uint64 and software_image_crc.ndim == 1 and software_image_crc.size <= 1:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._software_image_crc = software_image_crc
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    software_image_crc = _np_.array(software_image_crc, _np_.uint64).flatten()
                    if not software_image_crc.size <= 1:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'software_image_crc: invalid array length: not {software_image_crc.size} <= 1')
                    self._software_image_crc = software_image_crc
                assert isinstance(self._software_image_crc, _np_.ndarray)
                assert self._software_image_crc.dtype == _np_.uint64  # type: ignore
                assert self._software_image_crc.ndim == 1
                assert len(self._software_image_crc) <= 1

            if certificate_of_authenticity is None:
                self.certificate_of_authenticity = _np_.array([], _np_.uint8)
            else:
                certificate_of_authenticity = certificate_of_authenticity.encode() if isinstance(certificate_of_authenticity, str) else certificate_of_authenticity  # Implicit string encoding
                if isinstance(certificate_of_authenticity, (bytes, bytearray)) and len(certificate_of_authenticity) <= 222:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._certificate_of_authenticity = _np_.frombuffer(certificate_of_authenticity, _np_.uint8)  # type: ignore
                elif isinstance(certificate_of_authenticity, _np_.ndarray) and certificate_of_authenticity.dtype == _np_.uint8 and certificate_of_authenticity.ndim == 1 and certificate_of_authenticity.size <= 222:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._certificate_of_authenticity = certificate_of_authenticity
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    certificate_of_authenticity = _np_.array(certificate_of_authenticity, _np_.uint8).flatten()
                    if not certificate_of_authenticity.size <= 222:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'certificate_of_authenticity: invalid array length: not {certificate_of_authenticity.size} <= 222')
                    self._certificate_of_authenticity = certificate_of_authenticity
                assert isinstance(self._certificate_of_authenticity, _np_.ndarray)
                assert self._certificate_of_authenticity.dtype == _np_.uint8  # type: ignore
                assert self._certificate_of_authenticity.ndim == 1
                assert len(self._certificate_of_authenticity) <= 222

        @property
        def protocol_version(self) -> uavcan.node.Version_1_0:
            """
            uavcan.node.Version.1.0 protocol_version
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._protocol_version

        @protocol_version.setter
        def protocol_version(self, x: uavcan.node.Version_1_0) -> None:
            if isinstance(x, uavcan.node.Version_1_0):
                self._protocol_version = x
            else:
                raise ValueError(f'protocol_version: expected uavcan.node.Version_1_0 got {type(x).__name__}')

        @property
        def hardware_version(self) -> uavcan.node.Version_1_0:
            """
            uavcan.node.Version.1.0 hardware_version
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._hardware_version

        @hardware_version.setter
        def hardware_version(self, x: uavcan.node.Version_1_0) -> None:
            if isinstance(x, uavcan.node.Version_1_0):
                self._hardware_version = x
            else:
                raise ValueError(f'hardware_version: expected uavcan.node.Version_1_0 got {type(x).__name__}')

        @property
        def software_version(self) -> uavcan.node.Version_1_0:
            """
            uavcan.node.Version.1.0 software_version
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._software_version

        @software_version.setter
        def software_version(self, x: uavcan.node.Version_1_0) -> None:
            if isinstance(x, uavcan.node.Version_1_0):
                self._software_version = x
            else:
                raise ValueError(f'software_version: expected uavcan.node.Version_1_0 got {type(x).__name__}')

        @property
        def software_vcs_revision_id(self) -> int:
            """
            saturated uint64 software_vcs_revision_id
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._software_vcs_revision_id

        @software_vcs_revision_id.setter
        def software_vcs_revision_id(self, x: int | _np_.uint64) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 18446744073709551615:
                self._software_vcs_revision_id = x
            else:
                raise ValueError(f'software_vcs_revision_id: value {x} is not in [0, 18446744073709551615]')

        @property
        def unique_id(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[16] unique_id
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._unique_id

        @unique_id.setter
        def unique_id(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray ) -> None:
            if isinstance(x, (bytes, bytearray)) and len(x) == 16:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._unique_id = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size == 16:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._unique_id = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size == 16:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'unique_id: invalid array length: not {x.size} == 16')
                self._unique_id = x
            assert isinstance(self._unique_id, _np_.ndarray)
            assert self._unique_id.dtype == _np_.uint8  # type: ignore
            assert self._unique_id.ndim == 1
            assert len(self._unique_id) == 16

        @property
        def name(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[<=50] name
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .name.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._name

        @name.setter
        def name(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 50:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._name = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 50:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._name = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 50:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'name: invalid array length: not {x.size} <= 50')
                self._name = x
            assert isinstance(self._name, _np_.ndarray)
            assert self._name.dtype == _np_.uint8  # type: ignore
            assert self._name.ndim == 1
            assert len(self._name) <= 50

        @property
        def software_image_crc(self) -> _NDArray_[_np_.uint64]:
            """
            saturated uint64[<=1] software_image_crc
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._software_image_crc

        @software_image_crc.setter
        def software_image_crc(self, x: _NDArray_[_np_.uint64] | list[int]) -> None:
            if isinstance(x, _np_.ndarray) and x.dtype == _np_.uint64 and x.ndim == 1 and x.size <= 1:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._software_image_crc = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint64).flatten()
                if not x.size <= 1:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'software_image_crc: invalid array length: not {x.size} <= 1')
                self._software_image_crc = x
            assert isinstance(self._software_image_crc, _np_.ndarray)
            assert self._software_image_crc.dtype == _np_.uint64  # type: ignore
            assert self._software_image_crc.ndim == 1
            assert len(self._software_image_crc) <= 1

        @property
        def certificate_of_authenticity(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[<=222] certificate_of_authenticity
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .certificate_of_authenticity.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._certificate_of_authenticity

        @certificate_of_authenticity.setter
        def certificate_of_authenticity(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 222:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._certificate_of_authenticity = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 222:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._certificate_of_authenticity = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 222:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'certificate_of_authenticity: invalid array length: not {x.size} <= 222')
                self._certificate_of_authenticity = x
            assert isinstance(self._certificate_of_authenticity, _np_.ndarray)
            assert self._certificate_of_authenticity.dtype == _np_.uint8  # type: ignore
            assert self._certificate_of_authenticity.ndim == 1
            assert len(self._certificate_of_authenticity) <= 222

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.protocol_version._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.hardware_version._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.software_version._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.add_aligned_u64(max(min(self.software_vcs_revision_id, 18446744073709551615), 0))
            assert len(self.unique_id) == 16, 'self.unique_id: saturated uint8[16]'
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.unique_id)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.name) <= 50, 'self.name: saturated uint8[<=50]'
            _ser_.add_aligned_u8(len(self.name))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.name)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.software_image_crc) <= 1, 'self.software_image_crc: saturated uint64[<=1]'
            _ser_.add_aligned_u8(len(self.software_image_crc))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.software_image_crc)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.certificate_of_authenticity) <= 222, 'self.certificate_of_authenticity: saturated uint8[<=222]'
            _ser_.add_aligned_u8(len(self.certificate_of_authenticity))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.certificate_of_authenticity)
            _ser_.pad_to_alignment(8)
            assert 264 <= (_ser_.current_bit_length - _base_offset_) <= 2504, \
                'Bad serialization of uavcan.node.GetInfo.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> GetInfo_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "protocol_version"
            _des_.pad_to_alignment(8)
            _f0_ = uavcan.node.Version_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f1_ holds the value of "hardware_version"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.node.Version_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f2_ holds the value of "software_version"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.node.Version_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f3_ holds the value of "software_vcs_revision_id"
            _f3_ = _des_.fetch_aligned_u64()
            # Temporary _f4_ holds the value of "unique_id"
            _f4_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, 16)
            assert len(_f4_) == 16, 'saturated uint8[16]'
            # Temporary _f5_ holds the value of "name"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u8()
            assert _len0_ >= 0
            if _len0_ > 50:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 50')
            _f5_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
            assert len(_f5_) <= 50, 'saturated uint8[<=50]'
            # Temporary _f6_ holds the value of "software_image_crc"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len1_ = _des_.fetch_aligned_u8()
            assert _len1_ >= 0
            if _len1_ > 1:
                raise _des_.FormatError(f'Variable array length prefix {_len1_} > 1')
            _f6_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint64, _len1_)
            assert len(_f6_) <= 1, 'saturated uint64[<=1]'
            # Temporary _f7_ holds the value of "certificate_of_authenticity"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len2_ = _des_.fetch_aligned_u8()
            assert _len2_ >= 0
            if _len2_ > 222:
                raise _des_.FormatError(f'Variable array length prefix {_len2_} > 222')
            _f7_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len2_)
            assert len(_f7_) <= 222, 'saturated uint8[<=222]'
            self = GetInfo_1_0.Response(
                protocol_version=_f0_,
                hardware_version=_f1_,
                software_version=_f2_,
                software_vcs_revision_id=_f3_,
                unique_id=_f4_,
                name=_f5_,
                software_image_crc=_f6_,
                certificate_of_authenticity=_f7_)
            _des_.pad_to_alignment(8)
            assert 264 <= (_des_.consumed_bit_length - _base_offset_) <= 2504, \
                'Bad deserialization of uavcan.node.GetInfo.Response.1.0'
            assert isinstance(self, GetInfo_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'protocol_version=%s' % self.protocol_version,
                'hardware_version=%s' % self.hardware_version,
                'software_version=%s' % self.software_version,
                'software_vcs_revision_id=%s' % self.software_vcs_revision_id,
                'unique_id=%s' % _np_.array2string(self.unique_id, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
                'name=%s' % repr(bytes(self.name))[1:],
                'software_image_crc=%s' % _np_.array2string(self.software_image_crc, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
                'certificate_of_authenticity=%s' % repr(bytes(self.certificate_of_authenticity))[1:],
            ])
            return f'uavcan.node.GetInfo.Response.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 430
        _EXTENT_BYTES_ = 448

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8!)O<20{`t@O>7%SmS#7bG%f$6V>`C;-$|T=N+d>coJ98IM;<2`c`7fXi8C2t1~YV%EU8;2yE)CKECpCVbJ&Ff5EudB0$wb3'
            'VC-RG%w>(mF5sh&KKkg>z^8#1d-2i7eXr|vlTH2jCswlAFo5-%U4O4$y;rZks#l#=;~)QKXQKZ)&o@_Uty;ZQZppy4>+V-}r7lb5'
            's^4h(EjN_i&c2Ui-EH7w?TeMB?0(Z7`(yX-y2Vbu?0TLIx=yCE?`#;ft6@8k=`6XjXE(5lXWI5s)%HrBUz4Su$?%Lf@0UK8t)}m_'
            'Fu71(l0nP$J*sQhm;C%qS7;*h58Xd@JA2A@7zS>o9m-bscUbWjTqn7@o!lp`tk-(1jFfA3XqQ9c&)KD3IwPHf{hY-uJA0k|aof)0'
            '*q-wQ7Z}~D<z_%4a+k2>gTL}x?t&+4XS`4@$RI6}J>`lUmg~}62%WAdAYWCx6_y*=e%E=Sb9gqch>Dd?V;WEr3M2FP-Osz7L*-Uz'
            'do??#^;fjku3%?!4SUfKx*elj^Q+xXri*VA&YhR|=@n6MUUgn~#^XY+hlQMy^G3TOI|utjU9POC0i<FR&hyT3XR?hwsL5s^t2Syx'
            '_v_C7^1Qn&YvraNgk`tZ{jBqNx#hQms>Fo4EH`cBud|Ct-K}&xyJu0amS^ehHz*J74dmDHNlWrI?0K+)nH#?6hSZZ0ekxyRb)D(X'
            'u8LhfFTENnB@IHkAzLkb0d=DDbhBNlyVY_a7ut2=tT)`4npdNYEzvl4J0_2G>CMt)iE8SGB-?{!$8I6Rf%HNe-zB#yyI(t{&ex}`'
            'mV^D1II31lHf%3+s}?J*6_7YuSjG<V=Sj==>MK?>6c&z@70I_W@`WR<X5fc@)vsF%SW{rvF<;G>Ez9#mtLl4I8F-c(wq$+Yy5NS6'
            '6;c^HtU7U9CFDIC5@nzsHmVF_u!o5i$<C2z2+E;f4tzh1O1GLe_RM*&=)CWI;C$#zJE!p9Po2}wN6yEQD2#HYj)Hq7*7lyRp<u$n'
            '-`&pMpSt0v(eJbPleN8*E&I)G$J(lr)=Hz|<EWwJK{kA}B@*B-nkX6?{l1x|>bPjk&Tl)9&Dyn^>n&`^<eYPUmpuKp^TcTsC+dN>'
            'X_cMbszw}Wl3riQN?#q1eb%nm?O<g?>3n&~uD50PPu-#@thXvSfi)FdIAygfC_Ef<GH!gZm+4^_88|8?)h#qCmsuA&(=1VaT^Rg3'
            'M>M-G^89`mQEgomIDNNjSBx;-!*nmxeN6W=eT=Ee^l_#Km>y($i0Knd4>LW&bd>3nOrK)<G}C98KFjnurq46An7+XDMW!z?J<9ZD'
            'rmrx4m1&Xb7}M97zRq-<=>*df(>It-GJTWjF{W=ZJ<jxPrtdI)m+2JK6HHGs{Rz|en7+^S1EwD`on|`2bdIURbeZWI(~C?mGrh|6'
            'I@6m>Z!^8CC=@h)7>yr_@xxU7FcUw_#Sc#WupB?E#Sa(bhs*K9)%f9h{BSdVxE(*-<%c%<IJw-ky=Xq-cNHgyY{_ZIMkHGmXIYre'
            '3jX_QOEb|1%tT`|G1yG>0W;afW|C(!$+4LjY$jPY6P?XOV>8LHnV4)QCYy=LW@56Lm~18{n~BM0VzQZ-Y$hg~iOFVSvYD7{CMKJS'
            '$!21*nV4)QCYy=LW@56Lm~18{n~BM0VzQZ-Y$hg~iOFVSvYD7{CMKJS$!21*nV4)QCYy=LW@56Lm~18{n~BM0VzQZ-Y$hg~iOFVS'
            'vYD7{CMKJS$!21*nV4)QCYy=LW@56Lm~18{n~BM0VzQZ-Y$hg~iOFVS#%5y1W@5%>V#a1-#%5y1W@5%>V#a1-#%5y1W@5%>V#a1-'
            '#%5y1W@5%>V#a1-uD2a#6m8>zD71&xFtmoDHJ~-LDiKaG<Hd6iES5UUw5mS6(sb;4Z*d*3%iTt^E*rQ+#zi~+3>}wN+BG?DReW4r'
            'Z&;y!hO6+<w<^-AI<~ifr7qwiQAVq9DraH&pzV3M&MT#%)sw`ZgP80BVuwEd2vQAZYx(oxK(@Jm(J~q8Ny0he<Dd~OT@iR7PKXe~'
            'eK8i{jH(|XKntyyrKDn28CHath44(xvO|krg)X9kaZ4^&Wi!NjteDM-2+dF{nCyDga@83@%!;jsgo@hr8dZo3dJ^7OGVoiaku&ot'
            '=HwsRZnH^z6RNR!#3rhClh88`hac8`yC#G2s95iJ+<;;?N{ksBiTmWMwp<T^alKAmYBmv6MAAc+qtqZ`!}eBwLN7eOKM$qM`)#i_'
            'uDI{(R4k>^R!DlfA4!k)hPK*5B)a4he}suqQ~&2wG6;zD!T|NOwbBY@!zzAx`s|n$XScj|qk<hr)kHArl&lBQ%8^g7m|V6=@yC_I'
            '&(k)Dh0u^{Xt%I9sup*Q#yJuxVOwj#B@o&`3?8){%eC4L2oI0Mol7_^jhyX`xe{v_wUCw;Li5e{YJ$K<tbgbe+C5Ov@f5vEZ<p*V'
            'OJ&2nbF<kd2BA6Bq^cXPbkSXY;rv=HEq{|jga<yCO&PkIBTT(~o{FB^uqut*@G83D)otAHy|CM$8`cM~+pYoZwr9W%7Y5w$Zg#^u'
            'yW#x<*iC0Qe1P5Xz5(o(Wj8#^ZuroE8{RvB-3)fa8Fs_ZvKxMi-S821!-v=nKhAD=KfB>Q1K2IcZdhkG{2IIABD>*N*bN_LH~b>I'
            'VT;}HbL@tnVK@8~yWvrG!-v@oA7VFrV89LUXE(f;-SEf&cFVIHHrNg8?1nS3TUzb8rQL1M{X<(SE1&xlPvq+5#F>w*;;+tpG!{)h'
            ')|<zsCMsxMb)V)}oD-#2B|F9`7}M+Sd5JTvGWCVJUx~JdR7DmlY-H?edS8-W%@24omtLzKa5bUYW2)E{w~p38CTyck*XwF(QM0dy'
            '?`cX@vj?)*YmFSFT&TMXZUukU{R^cLO2^kVIq!OrAFV2G64!zphLIQLY15N9&-G1LrIAy}rJ7k?wbf-?OE?eIsO?AUDo7kS0jW97'
            'ZbY3+PezM>!2#+V`O?Oj2&>y_+FAT}%(m%Vv-lsFB93(q#2Z=B{JQDnG$u6Ku~pt-(@Duuug=pJ)ZoOEn!ApCPNLjy0?U`rtG%XU'
            'TTNmaX9d=^ZDz5I&^F9u(L0ePOUSF=dIBzzG?62VNzHJnG_fn$t%}Oyn|S8ikWcI;Yuu~S3JEaTG@sZ*7Q8=IFTUN&v*wm%#6Fq<'
            'Om2hc)NON%#}eq1Y6(+fD0I*A;&GaX4yn8brteK)(|wf{2WdV#yeSWudWh%x`>snoLG$EjEa@1cJy3aZgy!6*w&V$O#6ISM>lIJZ'
            'y#7o|UYI({KI)<B6Hk-Rcy3#MG1oKf_a3?p@htf$E0Ha6{ld4dQ9Mr`@I_URwH^P|`b&?bJ@Ep0-=lGxed9n<dijyHAzmVH|H?f_'
            '21{6&`zWt09$DMsWm<I<<9_m(jXm-<#H+N*dF{UYi6x4>N_ymch_PhlrN;Is)>-Ty--#V-SG+F9d6jqHa==pKydvB&p2UPG@oH1)'
            'K~ZVKn>*gBctcF`y7qx2f+Z(;9lYcGi8sYDUTdc{W*qCDjJ4+NN6Sl^lY|fPmN?Gq{0Ej7mOjqd;KBGzbD5S`T3QK@;%)H`<By(3'
            'O_ENX*u4F8>uDLKC6pek^hhObi+9Bo<DG|+6V@=rI7#uEmQ-3!>CsG&Wm>CJIu&t>e2Np|BxAA7_3Jp+JViS8ep+_vkxP$TTDvya'
            't$xjVE9$f2<|pDk#)1zmJ8_cg_;BM`r!{SBJ?q!9ejV%Aut;*mt$07is{Oi#Bgn`#BUT}!!K#LdYf#W&O~WkfU}^{sFyloS)v)9x'
            'urw@u8HyT~zXFpQHgOfEG%+o%!L%l3#C4d_#H_dhvznL_H(^c_=fo{>7tU$0tO-Zl21gT3aR-{3SVq9C4)_WPLoWW1U`T<MpF0dg'
            '3dz>aj~Ry0qAN3mAv*#?BH2E27-HRPTHFB`Vx`C7|1Au$deHGl14F3KN2Adl!jKq-C_Na$kj-I8T4OfCke%Y>QNxgL!{>v-kXWN8'
            'l}??wpZ5PR!H}H<A@2;p5an&Qhary&guM10!H|amA<sP|3?ccc)ki-JVF<D+3JgKkdLRS=2m%CxBHspwAPPY!vMCPXgF7RNY<Eg?'
            'ztJ+8nRdhWCIV^KqEjZ%_a<bc8Ln8T&YnJVMjcL3{*radvs4QGj1RP$GHAFV1qwvxb5YWR#%-Lc*Zm8a1+xZrHIzZivIBY2vM0W>'
            'ij)*YK^Kalx(q4Dm^C?Z!YbBe)os{ytL84aA-*i(D?c2wCXm`KXUr;F#kN<&0#!edV-)Ga{ZR*#0Ug;<XaL<<2s{~DHNRoIp2||B'
            'lS%96_L6Ni?do}ow;vm~WND#fy;$`dC6ruy-i~g61f^!+FUo32wAQYMFAf~P<@HQv^CPzDfg?6;agRQD2DkVaz52H2X^YSHn6Pwe'
            'YT(Fhy6?yg`Pvq$ZUCx1h}s8GH^R~ch#Cn5-JP6!_26a?SQZjEX$(XIWaxaKLE%UO19$a6UJu?Sz^w<<4kTwly%V7Q37FcOz^0J|'
            '1QinKlTSd5kw6uFAXXqFo=?s!dT`*`<V>Nre1AGwct4datDj8v<a^8DBgw+`aIz$QBH712lq?qyCJVa*$#U)SWN+6@7E_NU%boqn'
            '0%l*b%egn%&)k!^`H^JraCfq^S4j5rb|r2upX{6El3gt$*}Ka2ru5$a&|suN2DPzo>qN|KtB!;FCVCQzlIdL}*bt5q?LMf06iQRq'
            '35fZ<NvgV1KwaCP<Wr$3B%t)g0_x&{q@=oBKtev0<X0CANO*^nw$vp9;&(JDt1cSQFsrKuG`Q-r0S)OhjBDcy2Q+-oC2gon2Q*aa'
            'YX{WUiwU1ECA~SCw5qNjh?n9E2!uS<6$J4@9LPclSY1OP^;Q=VNWIln1X6Ex86iP01yXNyA%WCeT}dGIR+kczwS9rq`&iO%bv1$1'
            '`*<P&bv=R9`<+A<>WTuX_f#U46N%(cCh}2N6-d3`OC+VPE0B7BkjU)AWQ6$A0;^*|%=A3yfh67yz0ZOySA#0~(_b1K%t&`+q7W1h'
            'Jz2#K13Oqzp=I-JuNsBkMPYd8ctSrF+h;`;K49$I7n_H>VfmU2DH`&EBcr&NR7-w<WrBu^Y*SUKV9{O+SeaZ#2R9PMl*CbdHhIpf'
            '3_^00ttPtQdAHgNj<fpML1(z+)+80c(koUg3@8K$UwI*g=`6I-<)iDB<0EY^^0r}LFlbZ<maX_pa$Ln<#vM!oT_~on=FZPc3e~eJ'
            'ZI?=L0AJiyTw=81f-Nbr;=pgvbu$&*<EnVczMw&T@SF73u9rrlg-s-e!6Ec&Q8Nt`uCH39I{O1G)rfL1ZuDw`<B3WmGq|!@qG+CU'
            'hG_AF(xiYyiA$Gg9PL^Z$;rwx@6(Ej#%rOCqO4<mt#Raw0+~=8O*;r(ifTGJV&O`N*iSRw3-dhv`RR#wj!*ph<I+8|4k#=QU?9`c'
            'q@=nQ-3L?IrmV_JC|jy(4tAo;du@uoRhhAU5_T)Z)tL%>a=lILfv*Otz^B-{uv#m6k><EUl0%Ji>-AXH<Mh&QtH9kj9VOgGHCv+4'
            'vzly@s8NCZ_!?p<s{V|J0;Lcu>`v7Us_n)S<%(3rZME7;E$eZ=A`=SGWM%by9Ab)H9FO!u@vXWVRo>TK)ytl+DQJvh&f4L9FCzyd'
            'wf_3uEhGQBUF6lB{4nxr7<n~}yc$Mc4I{6HkypdWt6}8T4<Pbt8(zMb=&NtR>jOt&?I0hIJR<8m<olr`w7x_Bb~I}1JM4paUwm+n'
            'XfDX;kTD>Wr;`*N3I^QGK_M?pFm*5uF!N#*Ms*l9U^Fi*uyn8tu=1h^MIDL;6!T&dCUuxJU@|YJU`mH61E%s~8m4uaHefn0W?)8#'
            '83ShWVism~m^ENFFXmuQhdBf0^5Ptv)8U)}=kme<M+e6MCoh`N)S+oWGcT55S%+l<mh)m2R&`i4U^Oq+U`>ZL1J?3l9oBVNH()(4'
            'F2Y3}E*fw#FD}6)9WEJgDK9R=WgRXXa5*ooz!e>?7;q&ouEJFvt{QMPFRsBg9j+O0EibOabser7a6K<>zzrR47;qymZo*9+ZW?ei'
            'FK)pt9c~$LD=%)tZ5?hKa62#Vz#Sd#7zowGUAU{mU4xFPGFiyv=#;9Eg+h*wsLU*wIXa~p&BAC7EDfwISUD(aP|QLx2a_61W??c1'
            'QyNTVVJZjH8cb(lItMcv%w%CE2eTT?W??o5a~jNLVJ=5ubLX;fE(eYVP8OUTG&N{up_zka4VJU8oP$*jR<p30gEbA-vapt;^Ro3U'
            'tmojO1{bq%F$b44xRixUIk>FB<t$vz!4(azWZ_B<u4-^K3s-Y+O@nJ$xR!(K8eGr9^&H&L;6@g1<lv?TH?wdz3paCcOM_ckxRrz3'
            '8r;sp?Ht_E;7%6q<lwHBis-wWA4c>IBl?CBeZz>pVMO0BqHh?{H;m}pv53AQyxkt&ZWi4)gtre4Z|^7aZwPN64ZPhdN-!URTb;pe'
            'Ug6t5a2r9}2;v&w8@NSKi|CdhuJOYHw|DbDUVMw-79sAv@GZx=JWWv^6y0Hmvh2^7?RMzU!GH9@A*VF=EPwQ+FIyD$(wEIDp8mzD'
            'u{a__eT3}Tv12MUz-rjb<GoM|>x(VF+ceVqZc`NNY1b|K)U-{pmo2MEF`47m=Vwn%y!r0C?~KzS{Kuz1I(v#f&SYDTyFk$|HMtPT'
            'h{0;G(hU8Dz-~Hjm4Z^DFPf;Yy|mmw*2YRBpGtd4a>Q%@C!VYa{8*ZF-ll`{f1=a+!;AF2v&Da=KbPpwpXtxP(Vu^%KbnqzF4NOx'
            'ddkwDpJnmSU+C#?^mGRQw4HaqcBVdaPHgcVW9O63q2q5&Cf^%Ree2oz`5Jwm&G~fGk0*1HZl{oZq+B|`+~#}9n+Fn9Hu*Ghe{jJt'
            'XFBKaH-7lix%nBs_`TX`vhc0ddmCpSc+Ht7@$F=PX05%+>%q8RRkn$lnj6ceUoZX_s;J6;2NUjW%%6U}ctDTy-*r~dJ!~v6@P6?>'
            ';}SSiW73U{MK&ZXp3TN(3Y2tx_XdG&NKo^fv&Y%%nCg4?hn02yIkCye93xANjF9Z_dok(7|Hf=PV8ESSWw{*Ublru_{?6fYjsKqq'
            'LD`Y?b*T+sc(NWoj>y_JjtHIC7J)>c;izTy)2PLJqOEB7qS2;AYm-DOTKZpys#{O-VE_O'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.node.GetInfo.1.0()'


    _FIXED_PORT_ID_ = 430
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8!)O<20{`t@O>7)TcAoC(8IDF0-IipDYsqq3lD$Kl98<E^rsdTxwemVt%1_HkUWW;=8THIG*-g!K&vy4v<OU0H4+$t>faS&$'
        'K$ieI1-c~AQNbdCkV8Q1B|?w@IxTb*kc*Bw=Dn`hJwN=>ALWhLV?ca8-SzY8Rekm9tA5p9(f<A)tEuR})|-vxYEZ2eOM&G(X3hD9'
        'S*}^dQpKw`yub;qc5C-#%U^UV))&hStNm4b^jGa)whOJjCExma(+a{;NcZhjYwzXIZ&t#l-<L8|a?LuHbGT_PR!q0(dR43VCsugD'
        'o%4#9WFhTVuC!?Rf#bPU)X<lF{Z(5iBK5cJU!fW$GYoyF+zhRt{j+v!f7kC)d0AHSOG;O@8opIAL#x`p-Wo2=IZIZx)bRYU<W$=i'
        'Td$S^ujyATd{DDW4KuXctsxRMr`&Gsn!#o-&CuPiP<iG3c1yE8(mz|RJE6afiR+&0gr47S<@u^~Eoj?ETSH~Da@BIH?bcqhX{l}n'
        'fjN)rwhlL%<(gALo6R?Cq*<wIhGt|se43S(!J5c6?bd<QA50_`I$4}3Qfck5eTiCan*l2ATW&~QMjg{$ZE2;dS82EY>9c07W>6u9'
        'gLw_^qGJ9W-uC8<(6;a%c9CmUqZEGK4AIU;V4IktY#Bj_H!4P<=~ishowur^#x)!56lIkK2ZrBtUB{g-<}ZZw({|?V+A<c5gQkwn'
        '$Ff7u2$~JDIcCHptf_%jnXF+@Y`65N*W_Sxu|?Feg$?EyVpHH%JY1~Sp{VCdp;z)fFO13w8YUXUe!XBHwvX6v*hlR*@t<M8WgoMT'
        'N7mCy<r>=iop{Wbov>81+<7c0u)_Y|?be<jIpOEg@5}g;M|3M)@*3@yu~i|#a=q+fXJco9Rre54Wa6JREZ?L-li(s-s-R`7ZTpkf'
        'D>G)biWc3F$eyC77qM4Of4ToDmau5nnpXSQ?Se?H1!V+LLl)E)xn>!gTX)>HNYRD4L>EJ)x>v;!NV)SRYpG$n5za0)%Rw1)4C4q5'
        'urC6u1M5$%nu8<Xs`kP<TXJ02^4s<htD0{e*&N}rz_z`|*6mlRgSVJ-5<ItCna>;xO_NlX@8G4o!u{P9#&ZVNGaSzvQGNE$IK!2#'
        'YHs+{LT3?c-v3jy$UNfXf*V@%mfzdx-CeznHb%WFCQgBM8mG3?Iye&-MA?ex@fpw~oW@drLj&+Y2?6F-O~2Y*&}y@cjmgx_1?*gV'
        'w3TY(jYMhtDqp!GXM1*FhjDtxjndnT&9Y_hrzA~#-u`R*TGM{*x_$7XeP|0X*e6;#o2z$zu?yF+{_E#(LO|?VG))9n-E?VA;Q1MG'
        'j?-&^XpP488N@V#KhoX6rWuh|#rzjIUo?C#^eSG>n8%WQ1pcy7^{fEl9~u?UtysQmIALJb=8S7jXh(AlqPk+obrsw8dz;P(abH{Z'
        '$!+j%pSC}WY-gXb&nAHSQF3**3uLdIM}=@^b~i<9YnKEoPP;TkZCcuAvZ@P&#vG#27DB;}`W$-=@ZUvDB@_u&p|VVqRM&*YzcVD$'
        'Ya+|{he#@GBFE2n$-+gR<!+XHSng#x%<>hMI?GpC?qj*1<pGwju{_A~5X%vk-(mSW%fl>>uzZ8%QI>DAG+4gH@)*nGEKjg}o8>z!'
        'zss_~a+Kw}EZ<`}#&Voxk>&d=Cs>|jd5Yx+EKjri9?K6|e#CN;<;N_~u>6GO_gS80`2&_eWI4rhn&m7@o8=PARhBnc-eP%&<vPpz'
        'EFZFbEG6U=z8Hxw3h~8cd@&tg%*GdXe6bW?ti~5N;)`4H#hv(KJ-)afUp$O29`i-hp5cq~26$KjVM9l3=-XgJ>BEM?*w7doY9BU+'
        '7#mr}MuxGWF*eeS4VAH>Fg8+*4V|%}Gd6U_hR)c~85=rdLuYL0j18T!p))pg#)i(=&>0&#V?$?b=!^}Wv7s|IbjF6x*w7gpI%7j;'
        'Z0L*)ow1=aHgv{@&e+fy8#-e{XKd(<4V|%}Gd6U_hR)c~85=rdLuYL0j18T!p))pg#)i(=&>0&#V?$?b=!^}Wv7s|IbjF6x*w7gp'
        'I%7j;Z0L*)ow1=aHgv{@9%Dm~v7yJ<&|_@qF*fuV8+wclJ;sI}V?&Rzp~u+JV{GU#HuM-9dW;P{#)ckaLnmwqTCNSyFhIiq4U&l9'
        '@>Y*mkDZNy(bf_zE6*=Ckgj%Cm+`{XsW)mC5>TWnL^LDfN$bTiqwL}8a>Ek!A}&Lbs3PlSuDcD@?Ol<Zq@Rte_-jbSyY!=#cz?3M'
        'n+yAr&HjUuN>NJ^%{NeSS|UG{V$njo;`zwFLnBrxDLCQvxM-&Zebq3-h=GR=^5rqZTB=x$5X&)QHOHgnd_>U4P%o;vV&{?NV67q1'
        'f@ZB6Z4_9M@qS_XUQo<mnCnpvS-R6`klwVcH@U~gD`tcE7Iudh);zOn`D0PG&hNMasc!TzRxBU4iT5!a7pYXOMonrokZwoTLzSba'
        'ex!!!E`LHdT(3I~J(=^GZgos*-_@wtO2w@R*i<(G8|idyB|zf5=#YN2$%G^If6pbIfK(^+ahwLrL1@*D!k6bSj~a1u!)?~f*l--0'
        'wi(z(<5@;!{xi&GEtxd%$K-&YBjRizS)vk}0cOXc#SNo=j!a7A&X{+Ih1HR-Mm5KFtu%ewT*}9dOEfL!FL(M}nl+4S=(Ses@D}Xe'
        '_swNwz@O1}oZM77N4NU76)lNj=K7m)Um{~Tk}6KP+(vh~Dare!weOPEutI0^y%)7~m9lOmZIK&ZK{vee0)(yK4Xb^GZK#j1?e25K'
        'xjr|%i`}rwZg{wlu&L~Z_puw^+eg^a?1o3!4Ik)p!+ZJ&o5pT9#cucwcEhi;8$QHt_yD`%SJ@2@vm4&sN7yp#hE;aM@3I>%up54d'
        '-S7!^!^hYS8|;RUvKv0aZuoU}!z1j553(CRz;1Y7pBo-#H@t`4aK4YQW!VjD?1oi#!>QOUt#sVduBPk!ylF|4&;FVxa(Q$7!ly>z'
        'rx!jQjV2%C<f+N=GNP;I(fmp~mu`h{Y(~4LHRq~@Gp&UBe9bFI`y;X-0|#sbb~(K-T5i?zc`~=$py_ilq1<FCn`NhlXdnoii0N8Q'
        'PAziwb@4t;iE{Qp^*XhYgS6&r&b(8`Up4PqF;CC&cGa45+{lksq&A6bK@G#mi}JMTS~$;jO;>WWS<bAE-0LxoMVtq!RQHa$3Ni;y'
        'Kypqq>rvx+C!>YmVF$GieQDxMgvD(&?JWE!CfjtbS@<t}B2KmT#aq15{JQDn^mC!m9-s6Mn@&n=^43?hgS26{sC(`@bcsy4-2|2`'
        'U6p&fr?#5JQZ~Svvdt`(63T{|EV?JsgoLd8ttR9mc_uQ1n4TG~=b0Evwy2`~cqg9uHl!1~2#tH>vs^+<HccmX6M~0(%Eh~Tc-Gu9'
        'kJw8yfX;RBoVsml@k&B{dTPQaF%^1Ze(@^JLkDD94WI8xXwy^W75iyEJGiM1`1AnJ^-o=vc#Y=Ck=W8PMSG_F;t<WbuWzXnrigva'
        'GnXsAL-YEP9(&=_5%y8fRh~FZKI7=N`eLdh?Dw9#4)F&0C?l~gY5mp<mnhyO4|q(LV{E5C)qZ?O>Jx8~_dOBU+0_qZrMGvi4so2k'
        '{X0+W8O&i|>Jz-O*s;3B+qCK^#O>rh8{P3b#CK_x^X^l(6LS=Jm9*n}h|y%_CHwXSmRacT-|?4LuXs<4@hb1B?SQ$)ct!ZqbQ0sD'
        '$g52`4hnK4oP6oEiuc6?uWO&lBA9c6*TFAcKXFo=;<a|~h#AAOC*o1_y`9yiSCd2!@qswa>-=Z77v?_A+~C>t?A5Z@UcJ^zbQIqc'
        'A2R>wjHn43Qy*_$e{b!*HtMxdZ(sHHR8qJ2NK7){c`iF)36so|q^`Y|>a|mEZ}#?O@2Kh-Q<0{qr}$W$VJ^1$_&SXxPtq7W+iSbt'
        'p6l(m-qE%B*y<ixA4F}I+I%9u&s^}iZ70r989&_E*S#Zc>v7gS%DTr`_XvwDN7{<BF<0##YuJO#TvK8NQVOgn_;3|+3al!aWDRr$'
        '$pI$30V4|Lya|SanQuWs!Th&jLcuETz@#Fk#9f$D#I#t4X+_M4doZJjS#cj`6>&v85Rc)C0!xap#Y3<a(GZWIp@=0U%<=_a4r$1Z'
        'ZxRj3(em>p(~w-UwexMJA++d94QR+qp&^lNcbtY8Pns5A0u3>G`{9q4h8P{{_^qKK)aDaW?+$24Ohe>27|@W-X-Myg*+@fPmL@w*'
        'LtaGBXQd(Wh?<aN>f@)W|Nj#Wd6^{S!#)}!z0LMCWT!~TyI&Ixc^(pS^f_q=*-x%Mx@ibgkQI?*3bNWEAxJ=wAP^OK5gvjp1gXfT'
        'JcM7|Y0&`@dvx|Ml~iiFSvTEr-!iMwTPD|Y$E|uJTsF>KK7ZkYd^ttwi^e(EkWc7m{6ec?`E@6xK!ND}T=eK!<2KIKYTh+Wf=PX|'
        '5?X#>n7(z!Fvovk6zGv31zkvmYF0=oMvaN_kBvgrsyKDCW>lSdC&ZgYyyb<X#yCndut$v&9pI>9hKlD~qZH}F?U64geR^d_p#c=*'
        '?z>iKRK2?CxH3tB-b@;QYA%{a!>nAT11zIshE<#|8pkSLy@-};&Y96cAHUe}y#=chlB_l>;jzBgZ||t7)aI|)ruts7DGTqZ{qNuw'
        '-ltnH`aW&pY)6SHm8$A{Wj59I$_(||ma1+bsvU~jMNl`=(u9a=2?gDiy!YzR%?`25C3I5jiv~#1`+X*b`Gf`zbx2-^-X+AXL(}#p'
        '?|?dQfQAz?wI`uX`Gf@J66%vpNQ{<H6}2x`ASK>R-dS|$z#GXsh0gN*aI)}zJy}+NC)tzlEQ1dv3)h3mlJvD?ANxSET-={5?Di$g'
        'wO5n9T|HS$y^<_<hLZ)%-ei|^PqLr6J8|>*WbbfSva^><_Vb1kH<wNJ%`(ZZmX_>Yr8`r4XMd<a(jbMSv1{u@Om90J`}a-MBormp'
        'IX$o;93|R)kO3+5Or9Yi<@Y2{<v9Xs+HjIihNh5#dQTHj6Za)K<%t3^@_{71JXJu(JDAiZPZp5ABS~I)x`4V_o-d%zl_w0SOOG(G'
        'jZYa+_Z>~@kS7hOt9s8GP+i9oJ&z}?Ig!*V&m4&3@u>r1p7Pv*cq<NMAqFhZ9?<ZXrw?d&%ku{`yyXdmguUcwc*|1=G`!_G1RCD*'
        'Bto*b&(ZKcm9$%)N1)+-I<bH}lR(4!!^9TyTmlX6$;2ujCzd~x*hijEpyB=f#8UE%0uApUBsTkD(nC|dk^5r0<3aZ&@owmS=B-l2'
        'uaH0eGmV28=`30lg5shlD?6cY`pYu3Y_926qR_i23{Rd9?2hd-q5_{W_U((!!`(1{)e0#Z@|tZ$aW6eJc|PXx>oT%U7A1p4J2hZo'
        '))G3nd=yg>NAa2DIV+YQlA{b7=z`~*N+&qZ=u!ur;i6NuC<EqRHiFQn5Foteh7_hV-$a*>uGbpNH{HnFhF!s+Q5l%G>@8YjGX64d'
        'U=rv;F@05MZqA}mJ)_)oC<h1d#ZAQ}Mi6HVEDH<vy*iz@lEFQWjF;>R8pI2)L3hnsF&`~#A~W=Np<9irsiSc{Su2&<9bhSYl!I}j'
        'TjLy0RLoD~%4U(Gd3qB>i=X}@q-HgW<mACJ=h2FZ`fI+4rmSIk!5HdAflO$QhUte6MKztt8@Li8^?McXgn6F7bbkE9)8l{s<Kh#O'
        '_6=C-K;P<(CZ(Zk(78*QY|<z%hgKkq=3pl};M%0<TbUT^Cu0X8uFhoOljClJ2R<7o1D|4aVX;PZqgUfHSq?{>Q>(?c9;2IPQwHwF'
        '&(Xq79A=9YdRDa>WNI8hUVIL(7!`lPMT1g^6*i~h_?2dTky1rN#R-C@9G11XT@i$QgsfG$8i$x-6UU-)A@!C`jSBB-u54w;*c3EI'
        'F=x&2sh5%cky^k1`j(Nu-!Ag%QFah{HHf?#L|zRduLhA<gUG8v<kcYZ>KhPwwT&)+km#!y(Dj+4uwJ4bJ06ksHR}D`5n5lPelIm@'
        '>uYR-I4geeglH~EsgTkjm8CZ+D&#bHoPk_c=%A~hYoKSv2#lyOqQOX37+|PiXkcVT0SYP<G$>@n1Wc$fp}|B}Ov0oJlNwBB#S~1b'
        'Fr~p%R!qaR3ey@)XT=Q6s4%0!OjgXotO~Ol%x1+ExT3-p4X$K`4Ymrl26k37prJxTgGN>?!IBC~8Z2eS3aqHGqQOd5tiq}as~W6k'
        '#Tu-su%^LUR@{IaD%{ZEMpoQ}n=0JY;AU3bf?F!w(%@EB+=kmK+}7ZBR@{L*D%{cFPFCE7yDHq(;BHo|!@3IV8mwo<J-DaBJq_+<'
        '#eKN1!hH?yXT<|}puz(U9%RKsc&Nfd4IXC2BY333BMqsVcnptKc&yQDs#F?M8G1{VOG7S0uc-7i=oxxTHIjyr3>XR+X)rQSP@s^8'
        'LIx%jm`KA!1|}7lOv7XbrWBY;!&C;Q6_`%LbOvS=m`TG-24)qQO~Y)4!sf1|;YtQ<1?)7~8E7cbNJAq7OA0KdVJQPE3aq4IB?GGp'
        'tfpZ#L+{Jh(y*3+8w%V=!;K8wRN!VBZf4+?0=Lp|D+9L`xSfXE8MvdsoiyCZz+DCIrr~Y|))iP!!+HkpDR3_h_cCx_f%|EAoQC@u'
        'c%Z<8G(5<_Lj@kD;b8_IDex!_k23IB>51rjoE=2;4I=sm5q*P*zClFaAfj&&(Km?bdub7U1A4nXz1=LjZ$NLKo!&l8<llha?hL)%'
        'DoQXLkz19?ZC3KzE^-@D+lb<7e=u^3q!!sNQC#htMQ$HwzrFkx$t_acC-Ga3b2&^=9u(bShE~a&E1AvErWgOw2Z!v@**Ey3FI~x^'
        'u$Qi6M&bNV&W*+q8S*1!r%s)cp#etSTpH_yS{Pq!`Q4^`=etc&tfyHs=;OpD#a;$RfnqYpj7yi#ji3DJqYuaECH#-ie|q^GeVoaR'
        'KFe+SM%9}4tw_O&zuXADdEac<PKAO}qA!}rue}70Z&gQ&`OhtL(c*~L?oT`!&-k%4`90!=f1$Vaf3@(hC>DN8f9}$sf1^MDL4W?8'
        '{=B8)pLM!gr>o=iXFiR8en(eX4gWa!^T{7Iw%?ZDFkYoEv2F3?;N)B4x#YvtJM|Ia?l^)$%HEXMH-6*Np1FuOuFFj&1MeE0yK&;a'
        '+njg;?@n|lmfu<KyWJn+EAuumQDbA?-rEcRgQHQVe}oSnZA{;Ld*PHCr+;h%dV-A^`tC3Mcbo$!WqfpRW0nmM7J_t~Cr6LgcWp4('
        'h6i#=v;QLb_&TETw+RL#_(jNzKo{YSp!Uau-qujbS_*MmZbNFgb+A<BkJ<Yr+oG>XZTOOt@%-^Z#<uZ7=%ls?7`ljEmKvrmi}yZ*'
        'sPCe#riaER57}4k-{h0~oiFWoeZw$^iHG?A2eI)>m0#e~oS%HDzw49o3%{Wr{5Ab))1SZ7;=Y7`R-U3auVZ2FKA|_a@4{xe_<z15'
        '0)DY%000'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
