# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/dmitry/monitor/monitor_ws/monitor/backend/dsdl_messages/public_regulated_data_types/uavcan/file/407.Modify.1.0.dsdl
#
# Generated at:  2025-11-14 17:37:07.784505 UTC
# Is deprecated: yes
# Fixed port ID: 407
# Full name:     uavcan.file.Modify
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_
import uavcan.file

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Modify_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     preserve_source:       None | bool = None,
                     overwrite_destination: None | bool = None,
                     source:                None | uavcan.file.Path_1_0 = None,
                     destination:           None | uavcan.file.Path_1_0 = None) -> None:
            """
            uavcan.file.Modify.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param preserve_source:       saturated bool preserve_source
            :param overwrite_destination: saturated bool overwrite_destination
            :param source:                uavcan.file.Path.1.0 source
            :param destination:           uavcan.file.Path.1.0 destination
            """
            _warnings_.warn('Data type uavcan.file.Modify.Request.1.0 is deprecated', DeprecationWarning)

            self._preserve_source:       bool
            self._overwrite_destination: bool
            self._source:                uavcan.file.Path_1_0
            self._destination:           uavcan.file.Path_1_0

            self.preserve_source = preserve_source if preserve_source is not None else False

            self.overwrite_destination = overwrite_destination if overwrite_destination is not None else False

            if source is None:
                self.source = uavcan.file.Path_1_0()
            elif isinstance(source, uavcan.file.Path_1_0):
                self.source = source
            else:
                raise ValueError(f'source: expected uavcan.file.Path_1_0 '
                                 f'got {type(source).__name__}')

            if destination is None:
                self.destination = uavcan.file.Path_1_0()
            elif isinstance(destination, uavcan.file.Path_1_0):
                self.destination = destination
            else:
                raise ValueError(f'destination: expected uavcan.file.Path_1_0 '
                                 f'got {type(destination).__name__}')

        @property
        def preserve_source(self) -> bool:
            """
            saturated bool preserve_source
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._preserve_source

        @preserve_source.setter
        def preserve_source(self, x: bool) -> None:
            self._preserve_source = bool(x)  # Cast to bool implements saturation

        @property
        def overwrite_destination(self) -> bool:
            """
            saturated bool overwrite_destination
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._overwrite_destination

        @overwrite_destination.setter
        def overwrite_destination(self, x: bool) -> None:
            self._overwrite_destination = bool(x)  # Cast to bool implements saturation

        @property
        def source(self) -> uavcan.file.Path_1_0:
            """
            uavcan.file.Path.1.0 source
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._source

        @source.setter
        def source(self, x: uavcan.file.Path_1_0) -> None:
            if isinstance(x, uavcan.file.Path_1_0):
                self._source = x
            else:
                raise ValueError(f'source: expected uavcan.file.Path_1_0 got {type(x).__name__}')

        @property
        def destination(self) -> uavcan.file.Path_1_0:
            """
            uavcan.file.Path.1.0 destination
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._destination

        @destination.setter
        def destination(self, x: uavcan.file.Path_1_0) -> None:
            if isinstance(x, uavcan.file.Path_1_0):
                self._destination = x
            else:
                raise ValueError(f'destination: expected uavcan.file.Path_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_unaligned_bit(self.preserve_source)
            _ser_.add_unaligned_bit(self.overwrite_destination)
            _ser_.skip_bits(30)
            _ser_.pad_to_alignment(8)
            self.source._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.destination._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 48 <= (_ser_.current_bit_length - _base_offset_) <= 1840, \
                'Bad serialization of uavcan.file.Modify.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> Modify_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "preserve_source"
            _f0_ = _des_.fetch_unaligned_bit()
            # Temporary _f1_ holds the value of "overwrite_destination"
            _f1_ = _des_.fetch_unaligned_bit()
            # Temporary _f2_ holds the value of ""
            _des_.skip_bits(30)
            # Temporary _f3_ holds the value of "source"
            _des_.pad_to_alignment(8)
            _f3_ = uavcan.file.Path_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f4_ holds the value of "destination"
            _des_.pad_to_alignment(8)
            _f4_ = uavcan.file.Path_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Modify_1_0.Request(
                preserve_source=_f0_,
                overwrite_destination=_f1_,
                source=_f3_,
                destination=_f4_)
            _des_.pad_to_alignment(8)
            assert 48 <= (_des_.consumed_bit_length - _base_offset_) <= 1840, \
                'Bad deserialization of uavcan.file.Modify.Request.1.0'
            assert isinstance(self, Modify_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'preserve_source=%s' % self.preserve_source,
                'overwrite_destination=%s' % self.overwrite_destination,
                'source=%s' % self.source,
                'destination=%s' % self.destination,
            ])
            return f'uavcan.file.Modify.Request.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 407
        _EXTENT_BYTES_ = 600

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8!)O<20{_ie?Qa}M8Mouqb}mVi#w01NNT&fJTXHTAR7&Y5+@yxcu^XHh1@W@X?atkdygReqo%Q)5RiqLxsk9Q2vV1{+#7m*T'
            '2gDb?AfX~Egv39=AHW~M@0r;<@15-;5J*Idyf^#2zx<wO_R-PrfA-vz`&Yh{4x&7Y+d(ce#bfo5cVf{FLX)H>S5{Qz$r~b82_B=n'
            'gH%*ctEG3Ux2wf+Hc(oNtddjZ$vZYHLR(~FoaC86^8_MZDELmub-Sw|d&5MkJ7{l-w+fNls+<pYM3yU~Nz&Z?`uS<KKD|Emo$8&c'
            'JRWdsGu0`q$g8hG>>)OfsH*arH6`L`&yZFSamxcs)*Z&4X5^*X0mbpxjfn-<<K7$(I?4vI&^;?*9fXEFw?SeeQOS>&=WY)L5L^2?'
            '-fhq;crx|vYO5+g7UY)eh-Xn#(7Q!Pw#rj!CScBv2y#<oA#6ArL?*1t&)qOg8_P10m>t2a6wFh!*}Ysu%o-M&bikC(t>6(eT?Rs>'
            'd+iE>&wA74^YX>|>B9Q7d`W&%e#+}T3!zy*Lw17**-)BWmx)W|%FV9R);MNjSLHTe9vY)8>xiz&goIm8-$HrfHjg5xA5VaMzI@@}'
            'sP7mRp$6{bPcz!E^FmGrPQey=ZOoOq`l(f(Zr0Upj%dmg^4VeG$mdWjdwk`Khm=j0@j+Fdzt3@slUpt?t8_Y^|C51;MIyBIb%c~J'
            '+|#-0X%XGjR`f(RMh_R}eW)K7o$?rpCFP;AgK9l3&(zrux)i2b-pw(-m)EDMYCQMRpcCg+d1>guUj4usJNdgRPrR<I_u~$J))tjB'
            'fk~^99VR3nBpnkg6y3rG5{&pz(%(!)#;wVkjUP&d<jOCXXRjL_ax3(Kq~tVFW<pcng8tNI5yw0m?4z6wc6eNf>U-7V`ur1Q{wsAb'
            'z7DSQTU__VmPmzFhnch;Bzza41w+?YkQ&Nz@k^9OAJPNJHXhBCbJVy+%t5+7O{7y#a<sJAO}Tamv{`fn3@MO}osGvcvfm(-5Al{H'
            'qX>_tuJC-7E|l{K3H7;c6#qnOeMx}z*qt|SuWqg0eRIq4OI3bim>k#vL?A=PkZFF)MViN>Mp5OlZpK48MTN|-)z5fe9(m<jMK$CM'
            '{pP<irnRy9Ah`9$<`?dMv9?Bjw^kv`a^~vQ&y0kLa-o6AL1*A`o`k+FKQF%}A0Z%53Ls`A;09GlR6Q=AMY->aC`e6a1GN2S`CJWm'
            '0d;WT0$I+{pICKJKDRM~c3odTMUtnl02QU7fifE*AQ`%LE-_kBDU_}HDd^{we6O7A@NipbV9QAgXpkV7yoUh-7$`cZ@*opEq#u^;'
            '%?7-k^^gKhWD>YZefw&ArA=ZgOF+I5NS?#mjIe-ETLG}&m6sm8JTo=53A`j+rWw#$Wh8~=1Dqv{9AiR<m<ka9o87y+_G+8m1;`p5'
            '4;VT?MJyK(Ox4X)?f@77+sDjcdCYUkE?&7vVsk(&33g|TI9viKcQHF@AP`q(Ff<~C;6v1aEz((RLXYDZ5`C#cNh%`IRX{M-8TjEs'
            'LnvEnx3&a=gPQYlVYSHFqG<Qp>|(nOb@1K|rXfE@fcuT!L~bYqi#)c{6g>&SP?Yci3ng_j`R+U`Xk~ydw9F1-NhQn{Nr=$!Iuy~;'
            'Yc0kuvsE9u)F=??9{I?9WDzFLVx_m~%*PrkV{Z!5&-x0Cd@ri)!v*d|3sT+5Q1ITHTKd6~Ta-%Ri%N<**&be*+n*@dp)|SBjOSpq'
            '8IQze)9qr2+P=UsEnSFtN5vQuUVbD*+EhQ>vvP`ei-OoUS#B?56A>g)=SWtq)|b{uHyRj8M!zoC$>(uw`Z@g>al%5QEmxX?!iQC+'
            '9H51wg}QNW`CKyt{ZPg;q?CFH?iG4F_o;wRO|{rJ?E2~^Tf4ykQ|Q8WRi1Wm;de}py!)+gvh$9*#uw#zhYNu<0oAl)%`r(aFn_Wr'
            'e=2__e=gsXzrg=r%J=23<gckk<(9nXvFpLuBso=YC;KJ{-hLIEXzE{A>+{7p@;3p0wqDWpEheww<?-<~iYSEq0lojUJSUgsqWrUb'
            'RsKbOSjZnfmOt8*KR(0_`I~a#m6dD5b$JYd<ZmAXZT>MkHMPODN*#<LU9^_rp$R#NZZ>GM)ijNj$cIgW5*XH$q92q`s&y&`wGG^='
            'cfVSo6GA1_=#gbtH`;?85s>)4!dVBVbi1Gu(J~a8x-UGi3>ygXM~5d)h;hkq&5xWUD#Rh=7aE2RkEkJF0Cja<q%=SrWVsF~bR@EP'
            'KqcF79cot{tJ{z1C5nrT6V5mw8z5ICX>0}_{c2}5&^fR7TAXpJ2M04<3-f7J#(~r8lp&&6Ezn~R{c?_5Q$Flqv<s%Opq`4{;*z&p'
            'YY-)NIrNI<NiDqYB`3I>nWTZp%kDYE8*QPnCoSS;-TDu9D_Q^)cw;hbSN=u-?P$WT0z5co?eustc<-|wVWqWhlP}PV4uNn$TL-&^'
            'O6aRxEVl><5(V1`f1s;37{ziJKlm|>4Z#Zr1{;M4d2?1c0!#2`8E@@bI~+^iB4;UGFWlWmSz^Y%)4Yc`U<2OqG|dbTC6%x=eL-Pr'
            '(U^&yqjhNNffr%&#1896id`!(<!e1egCMkBj>E`<evV`c;>G)<1zjoC*)lF*IDr$H%D0CFjbK=gg~OvB4?|OEiyGX3Cs(c`-k3Xg'
            'QW2t;8<)5}IGwy|(F>YYbtl&3krBQL+)d2a#Hf9I`;i00h{fL*<oLysbz|Ne-5SA25DssA%o`f_-}{`M2i_M)ttmd*rdqV6D!1Nu'
            'rNg+0oLBm?(?eMpLnp8dM$qD`9m@p)6}y;hgOpuPFD?<xm?D%Dah{B+b0R^e_GJNOVFwK>{h{}KkxJ#t2>h-PSS~HQ>P!fqRlQhQ'
            'm57n4MH-Q*lOiW`h|oLLzF8*x{NG27u{Bgg?)Ev{Wr0UfitUfe;UjAHz=(_ocVFm75ne+*j2iENpd4&fC4YC&o-petB<=#kPf9}m'
            '{@>mW{y2KtJNt$w3+e9q|3}%p=1$X<`A_T9ZflvAJNQ3bTK3WTOYIR59oZuq@=hE#c`uB38HiYu*KbP`$A9p|i`b#wpV?16d0vyR'
            ';CN+jKl#MDU&Z8cc|xA{-+9hqwOYYy_2GZIZppunRxA0p|4ylubGXM-YgQW{oGH%%GX0m-ERdK`_%r$8hv7p0C4V75uu7XX(aa4S'
            '|74=;r?)m9969iVh%7b{&kxSHj~esMj~Xru^z!cqyd>84KLPX|wn;t~000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     error: None | uavcan.file.Error_1_0 = None) -> None:
            """
            uavcan.file.Modify.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param error: uavcan.file.Error.1.0 error
            """
            _warnings_.warn('Data type uavcan.file.Modify.Response.1.0 is deprecated', DeprecationWarning)

            self._error: uavcan.file.Error_1_0

            if error is None:
                self.error = uavcan.file.Error_1_0()
            elif isinstance(error, uavcan.file.Error_1_0):
                self.error = error
            else:
                raise ValueError(f'error: expected uavcan.file.Error_1_0 '
                                 f'got {type(error).__name__}')

        @property
        def error(self) -> uavcan.file.Error_1_0:
            """
            uavcan.file.Error.1.0 error
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._error

        @error.setter
        def error(self, x: uavcan.file.Error_1_0) -> None:
            if isinstance(x, uavcan.file.Error_1_0):
                self._error = x
            else:
                raise ValueError(f'error: expected uavcan.file.Error_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.error._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
                'Bad serialization of uavcan.file.Modify.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> Modify_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f5_ holds the value of "error"
            _des_.pad_to_alignment(8)
            _f5_ = uavcan.file.Error_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Modify_1_0.Response(
                error=_f5_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
                'Bad deserialization of uavcan.file.Modify.Response.1.0'
            assert isinstance(self, Modify_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'error=%s' % self.error,
            ])
            return f'uavcan.file.Modify.Response.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 407
        _EXTENT_BYTES_ = 48

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8!)O<20{^X6+iP4!7*A@GY?3CX#HNKJJtEW;>&d0I5noE&Y|669?z%}@M9MH{&t$)$XU`nYnUiJ<Li<o@aiE1xAAIr#UaD3f'
            '#1}yjEQ<KxgRP+Wzxd5LyPHkBQ5Fnrc6Khm`F*$FH&^%HJu%vs{HbF>!;M_eCJ_rc_4pO)c+4hMQ4d7KCDUqbiFv$^LwCIqFnvd#'
            'xTfFI(`t}#-)EtQJ~g%`!?-HrknP?wKzv$9h@&yxs#4$H<cPg0T)x?`D=Z3xAK_|-Y_Txn!Z%Pu=bPg@y3k+fds|=AYLrkZL+-?q'
            'Mf#%Ni*tLERs+kNdF~F85#mxwi8SnBD4m26b+D6HE(`@)a{$I$7sJ7exb0AL`;oow4MO7{zJ>QrZuk+e`OMAxlGRwa+a06C;gWdF'
            'uSw8_31n5JktB8DBCF@rRJjFYj@emUTQy7QiN5Q)qSZ4blGJx;=yn3#h#fR#V2gS&GT2XCQPrwX<Lso$WYNWVMz%@75qQ2iI$oH7'
            '7vM!WnIh~f6*Sl|gMn>gJ=?OEZ3iKXOjveVo2gKVbJT00!-5*#3~ANOM!3G*9OJs`pVh{Q$id6z{)@}lMzK&VT_}=VrBbRSv|s^V'
            'ZC(Or)xeq4r%#>k0dcrkS|`h;jp9-lwEp=XkTUtwp0xUVp)|Ib&F0qD$WpGD&vm1<Z|+nNa0l`Tm9ONo>!r#Yh^EfwZDyaeuq;?T'
            '!1A?1M%|gqA(pZwe2ZEEm0(Gr(h3CkWn@W#vn~%=Rf@2oA7e8=*Nbua;`zmu{1U<c8#zN~A!pZ+j;S@v$b!Wq%NNqZWaF;2DMF;e'
            'EJ?!}lj*Lg5h3*_X!H`S@#XwVj;xnTWM#2(F4xV;^9#K=xwNrPO3P%eyqN8d_DU~KGD*3%Q7)G%>)kWp)D9d|lN~xpoJK0H2KFU5'
            '24`R%&OsJlhgEnJE&u}x0xrQ7*n;bD4Q|0Z@GjhqQH5NF<y@th68feZC!2hmxg-#wB;3_Sb&y0N4y%lqAP|!zS`C>mk2_iom$5Hw'
            'm(A=Q)U^H?)Ep2-<p*69222|@R2M$S4AN?(IU<)M4foWLL#vmV?_yIi!b0jODzt{8u8sz=<MAp9SuOSqvmL?4)xlJ!@g_q_tMNpu'
            '?KykaHaJ=ub(|zXBcvNLUmAtp;#H<^V&csdS!B}RfY~G1cVbUkViQxnBg-riurQG`TdRr0wP_Rd5zcg-=_gnWq#c8)!-<oK6eJWv'
            'CTF97;_dM9G<*V|!e?*~KF7}&@Fm=buM)cZiQ}PZ$6Fe^qv%LpKK@&)1FvzplKfs{Z8=v@5fNx*?FAAw>W)CaqIXtVU0}yD7M2oI'
            'k$OijuL8%02@llMW$L=zuRXB|ele@X*z;)EczhKWZt3a5#O=tzb{?b%x{!$-w6o5A)9r9Tx6NS4bUchQ9xG(bvA)|8_Cjnj)K6M}'
            'F?N#r!LG*Ari_IVI~3l-i~fSC2tK$09~R-GJ^Tw_tI3yV7g{fkU1<W}+(^po+inpZOi!53)_R>V`0ih#2;ajGsr^5~Pi;5-+8+H3'
            'zZ)mOL#+Ep`1u2O{@FGUM)9>VVO|+9)q`>H_y2DQ28C@)Om)3_wO>u4M5J%NkN`Ff{7RorJ33~ej-4p<8*xh2tg9y;s6+SyF;e4q'
            '%{(=nCLY$TDKYr1Bbh8rrd?2nE7Y&C3JaLzd!_NEG|6W1Kqpq_cH;4eMR<hvnJ~07FNp_>nv3suSu{uOe*nfWF}5@d000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.file.Modify.1.0()'


    _FIXED_PORT_ID_ = 407
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8!)O<20{_ifYi}G^8TQ(V?QC;#5_(airiXwkn>y<xZAgn+Ra?g{mhH8*w$oCnOwZ1o-81&=%rF<*n{r937RAz_7IiA%3zs56'
        'DdqA3@r4gmLPD(&5<h_-z;8f2?>V!(v+H$&DU}+@$K!K(@9*=z=j7Ircg7zcQvZ^N{gxG4PRR&GU~|X5$!m@%8K&3tz0i(Cn%uJ{'
        'f^FLr>n&fTZ>LkQrr$~@lM_ZDz7dNsG9sFnL&=Hj!m*n;V)gDEHEh=vf!eYb1+f{$K_9WBhRd5^^<d1mP41TJHe^`#EW6$+RW+M5'
        '88@~?5Zazgl*Vpk-*2ajg~g%ormsR!gGW(d*WyTo=}RDcfNq^#X>xSl7LL^wq-a<?;##GHj{5;=X>XHhp7lIOaJN^RdyJYL8IEup'
        'k%V+0YI4}A=~=MT`Q*OUHUT<Tn#I~OEkTo^H_~dFe9j0X?pi#s@`U!{nmm=9@&f^JwuKRTabQA*BZlRfY4YTCkGWpN0@3ug1&gF$'
        'dPj+Egu-Hx$4t*}G20Cz!7b+188+H(qm+X1gIaX?kYw4{7ZwZhi*iy<X}<S@Xs{E&yM_gC*e;KhCmu~MEz}ja+%yxrb{K`zZDH()'
        ')kNJ3goIj(-vi0<Rc={e-|GPRQ1aklt8aU@g&4SjUwLao&hsG&I0RYbQ$4C2&%RD26ZyDW<*=qaEzh<CN8X2E>7Gl@9S}A_z*}i@'
        '{|$~=%q%Itlxem<HH0IY!fmI<`Q+?|8`=$5SPO0>8Y1Y~4;99>sc*-%<QRg*=cXOC(nUWxlX>5$lbJGlm7a5tEEXtg^ywo;%?Z=w'
        'k+ufi_<=G}|KDkH{8>BFdaU8kOrm7O@ccAk2N4Nd&6?-f2)eV&a4_scPG9jwz#}inC%!3dI9Gl>xp&rcO&$q%;8s$ab_T+wyv6=g'
        'mDq83(Au|i)Y#@uEYdgA$;I)v;Q5y`W0*K~f0erpQ5C+3?1MzwGMaoBrp19R9YJoJma<>dc9Dnlfo;pTMv^f~+}PpRx>%sCLvMvh'
        'X|d~bS0PX(t_cWo6W(}b`SytXW^SYW4pxaWg7Ap10#8Tj1Iai{LU|tLg1^tTIwWxP*xKA`xmsRdsjBnRO&)4H2XX)rNRS?68m}r#'
        'bElIiZgQ+1aFb>cA>;GeH`bHk$FHRnLrT!s?<P!fx%`5$G*@|U{i~TYGRauT?<XUdFJI{p6Uo^eCL6Vu#(5(8nw*n+@(uYT`A!VP'
        'v;@?k2(i-J$w`F!uCNT>3nBw)UrA19aA!~k8_JN$82xhW8p3B4rD|8@_1kcAVFsuuJt`=p77P*~YsZ?NYf~sB#q7)22~+ugGFIc}'
        'mT-YBC&-{i6UO8X6cE5bTtk$j&NbkENY<?lSRK`n0!}0nP80jm<<g}Rkx3&0^0S8IA*2lm3qoB*(>?j<3!fhu8ma&<374q`6w8dL'
        'u&{->CL_g|a7|PN3xLfw*5{unv2}o~=Q=Hh46rR03J|8~W_G9m7y!G2n!!Schmu{Gxj<w?Kr9hfbCZ~y0w~u}JE<VhslY?guxuC~'
        'q*`o}<{Zz|IF2H*BW+U>3ro~(AQ-E)ba9~~6ik(hRRQB5<}_VMEkZUaN{te`P%42Pv{!|xeI6x1{f*p&Z^#6b+=-+YHzWvyQIofr'
        'DJhdlccocOEdzKVWwv2U3Sl-$M1%{iO<_%arO4PtR@SETJsX?c2I<JPWnm`H9NXQZIc;mObhIdNKijc!kaw+GI+$SBTA-?C+Jw6+'
        '8TG-Gi{wh+i`|SfXKQ$6s(&J5o6-w~%Xo-`QNS&6(W}={M57&nX==`3^P26TOlbO+5PqJ0yUz;A-bFIvju(W{MRX#9D7qn>m9f>K'
        ')!~f<hLe%6)0y+R<9ItE{py^Agq|C5+a;s$c9hu)&`eQ8+$goQubBt_V8#QulyV5_#qL(9T>+jh#o~^~X3G^ef1LrQkcFi*nNV<{'
        'dr=pD*IiwI<{eRqFOvHeE*Oz#P)w_%Au1^f<}W7YFXemkSMq)NYy5m5e<Ob@e@7`QpO-Ic?0TuElAOxAlYJEgs~nxEub0!s@wgZH'
        '^MF5^wP^bqlV`AaPj4GVJB0iRt$#_Llb7X1`H_5D{!M-y%b(qr?^fi`4^Tt?J~{jNrEBeWxd(ydA8rF}{xv!@w9H-GS1<;5QCo(O'
        'JmkQ-L94{dzVFx~Y$pjqpdC{-{XzbuSf^mHw}4w&@0Sr&L@0!EIWn!{#?@d)8;Jaljky{`sn@YfSkqwWWqF~2rJX>qKQg?jh<M5w'
        'D*54)rfp&p^kWx-wx=i|AOK}`82eN}6lAFkh+RtrPK!b|r#je{)lt<S(;|Y4gcC|QAR8c8G=0ZwY4ppKb%D-d*4JW=Q#>e`sYei>'
        'T4hWqzKR(viq---c2hU!xLt+q3`V-38VkxPOEoTGsW=Z(VwZ!jnC|Dovs_Yy>w(wIA@a2PHnHMH;MkB6>=vo^AIBq61fW10FF<#t'
        'Zv^0uB&^$j2X)w0d^8!XYp+{qX(QFi$H+y6K$xJegDoKvcI;407YPWOHe@6G0k1}@W6QSvphw#_1TQEUtYaehO-Z3PL<D~k<HfGD'
        '?XsjLQj*g3Lfvibhz_IQ$=^d1umSJ5?*|??C55o`b_AKJNM*)Rie{$C3Z8|^<0!1}FjlF+Y#r++5(K8Lb4*$q^g}pP&{?cEi{Rx`'
        'oK52bh8ZXk*x^<?pka)Nqv6n~$4%3V-3T$b3{7TcVQ<u(HD8#><=iE%3#a{8En1*jm1SbK-SUJ^0(BG9G0{mMoqnVM9Yo`=1G4vG'
        '$?6VobZ(6}NDvNfw9RuI_uu=JoCEKRozxU}mMJ40QItnociT0c*iu@#7Zo4!LJvCONUH-aI@-}(5KyrT%`I$Y7yS!U1T$W2%04^y'
        '+f*shgs1j-0bvofa#HF^t@$K{%1j6RW(X{&rd4z{37_q(v5M@b=!hEo7Kz$Vvfqa=y<)ACrBBaK-)fA_BO*f8&*3f$JOWd6e-sXP'
        'h}nS_={4>?(|0U9k9g=L-T<QvmMWEh9MmU_>I#XwK>JBa$UhyrH~35Et2-z3Hc5Ba&)&}bHMc-l=D#i$RM%3Fui&TMwCvlbFSWzi'
        'G~C_PKHE2)KYPA&mSGdipVi$`-}Hxi^CWtx_eS>b?w`-LU&8dIvHjco=5;G3C*)~)uYTt_ht}#UTC0!$*LF+(z0+FBfBb(!Eg8c-'
        'o>DVi{_sq4A0Sh|qy~mWg~G4?haZLu`3-#`9~h<in8^Ev^*)(|+1K{+3&R5+MC8p1?D^pt^{6qPf7DQ3pv8X<SX6H*CvkH|WpqQ4'
        'i9eQcE9PG2&JBF=)yLAd(+0ljoz9<}3j#FhcX-sx*={2Lm~m7;CuJ@A>v!8eys|jp&7*MX&d(=3Bu;Ep7Aq^ySB$x8wey~nr*`zq'
        'SFb*H^$-+~RaVxG`IU{z^+B>-IRvHgg_Q%vDjY_n6Xn_2xwSRp`dnpUZje~RmmfO>x#J5UwNRa#U0<nwjUJt!StyATN@7G!8Wk*R'
        'S!Yzg!B9oGE*7f!Qg`>T@8+KNNpt1$VU$~_+$b+CTsJUo%#k?P=1L8SqY5+KJKKGZeyO3JH&>W*caMEy9L8BE=NFddjP;cjW2szy'
        'Zf=l~uUtEfkykd>jg@(0ZM8f*nA#JEF%kvk+Q#bYN_Bm31U%Lyr=fUru`o2W`5X<aG%V5ZA`LfauxNOh2A76S8g^-jXn2i=Z`1HS'
        '8un=TAq^=F@6zyN8a|-mJq!T)y}R72PbygHzf$kP;WIt2cL1!|iRc2rdoI<T?)IRT<fz82Pu7RzQF}tycU=l6P-iCwgEJwY(3q)^'
        'kCOv7KO);agCRUr5q#<{MR2?W=$}Z@%|Ao3{mSKZ+I*UJWJN<M@|n<U^I@=FzE#*{B;Kc2#L@d4T*Ge_?oh*jS~xIF&g?JHX}6i`'
        '*4J_D9n1bpc;AcH=98p3>Pyfm?YS4P&7ooV=ilU{5&9|&tL%iQmVZ$AFMPFk_eSi_4vK4~{{XR93#t<z000'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
