# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/dmitry/monitor/monitor_ws/monitor/backend/dsdl_messages/public_regulated_data_types/reg/udral/service/sensor/Status.0.1.dsdl
#
# Generated at:  2025-11-14 17:37:06.192110 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.service.sensor.Status
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.si.unit.duration
import uavcan.si.unit.temperature

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Status_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    MAX_PUBLICATION_PERIOD: int = 1

    def __init__(self,
                 data_validity_period: None | uavcan.si.unit.duration.Scalar_1_0 = None,
                 error_count:          None | int | _np_.uint32 = None,
                 sensor_temperature:   None | uavcan.si.unit.temperature.Scalar_1_0 = None) -> None:
        """
        reg.udral.service.sensor.Status.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param data_validity_period: uavcan.si.unit.duration.Scalar.1.0 data_validity_period
        :param error_count:          saturated uint32 error_count
        :param sensor_temperature:   uavcan.si.unit.temperature.Scalar.1.0 sensor_temperature
        """
        self._data_validity_period: uavcan.si.unit.duration.Scalar_1_0
        self._error_count:          int
        self._sensor_temperature:   uavcan.si.unit.temperature.Scalar_1_0

        if data_validity_period is None:
            self.data_validity_period = uavcan.si.unit.duration.Scalar_1_0()
        elif isinstance(data_validity_period, uavcan.si.unit.duration.Scalar_1_0):
            self.data_validity_period = data_validity_period
        else:
            raise ValueError(f'data_validity_period: expected uavcan.si.unit.duration.Scalar_1_0 '
                             f'got {type(data_validity_period).__name__}')

        self.error_count = error_count if error_count is not None else 0  # type: ignore

        if sensor_temperature is None:
            self.sensor_temperature = uavcan.si.unit.temperature.Scalar_1_0()
        elif isinstance(sensor_temperature, uavcan.si.unit.temperature.Scalar_1_0):
            self.sensor_temperature = sensor_temperature
        else:
            raise ValueError(f'sensor_temperature: expected uavcan.si.unit.temperature.Scalar_1_0 '
                             f'got {type(sensor_temperature).__name__}')

    @property
    def data_validity_period(self) -> uavcan.si.unit.duration.Scalar_1_0:
        """
        uavcan.si.unit.duration.Scalar.1.0 data_validity_period
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._data_validity_period

    @data_validity_period.setter
    def data_validity_period(self, x: uavcan.si.unit.duration.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.duration.Scalar_1_0):
            self._data_validity_period = x
        else:
            raise ValueError(f'data_validity_period: expected uavcan.si.unit.duration.Scalar_1_0 got {type(x).__name__}')

    @property
    def error_count(self) -> int:
        """
        saturated uint32 error_count
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._error_count

    @error_count.setter
    def error_count(self, x: int | _np_.uint32) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 4294967295:
            self._error_count = x
        else:
            raise ValueError(f'error_count: value {x} is not in [0, 4294967295]')

    @property
    def sensor_temperature(self) -> uavcan.si.unit.temperature.Scalar_1_0:
        """
        uavcan.si.unit.temperature.Scalar.1.0 sensor_temperature
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._sensor_temperature

    @sensor_temperature.setter
    def sensor_temperature(self, x: uavcan.si.unit.temperature.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.temperature.Scalar_1_0):
            self._sensor_temperature = x
        else:
            raise ValueError(f'sensor_temperature: expected uavcan.si.unit.temperature.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.data_validity_period._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_aligned_u32(max(min(self.error_count, 4294967295), 0))
        _ser_.pad_to_alignment(8)
        self.sensor_temperature._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 96 <= (_ser_.current_bit_length - _base_offset_) <= 96, \
            'Bad serialization of reg.udral.service.sensor.Status.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Status_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "data_validity_period"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.duration.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "error_count"
        _f1_ = _des_.fetch_aligned_u32()
        # Temporary _f2_ holds the value of "sensor_temperature"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.temperature.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Status_0_1(
            data_validity_period=_f0_,
            error_count=_f1_,
            sensor_temperature=_f2_)
        _des_.pad_to_alignment(8)
        assert 96 <= (_des_.consumed_bit_length - _base_offset_) <= 96, \
            'Bad deserialization of reg.udral.service.sensor.Status.0.1'
        assert isinstance(self, Status_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'data_validity_period=%s' % self.data_validity_period,
            'error_count=%s' % self.error_count,
            'sensor_temperature=%s' % self.sensor_temperature,
        ])
        return f'reg.udral.service.sensor.Status.0.1({_o_0_})'

    _EXTENT_BYTES_ = 63

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8!e|$10{^X7U2h#n8MfQhcI~Dgq)j6s$W%zJBbvod?9?fU#)+L^o!YUSv;sjjncW?qca;6=%<PFzl?rkJYNU~fl;MIaZV~DQ'
        '_vJ(4Hz4r`_z_(4%<efp$6pPquynM$^Ywl`&-0Fdb?SG2Iz7?+x${*&HE9-cBefEl`b@-`jCfM!RcVx!-kn~Pnac5+-tAY?KlK+L'
        '`Op2lo8qb{r1mu7PT#S*PHe5^!6h&7LgYB&yq4XlPPND)nCYoR;#rtdM|Z5SwefC-_oOzeEW&Zq9}nK2`p!gW@;CmGcXM1=t5sZE'
        'Y5XTR`vk}LS9$lsO(nB*<jpKkg%#We7iqd3q*?dfTJ#c8L`Fq*p=^}aT3A?*?j#};i0>tOxii_B2yW18pLlv>u=U(YK2$p7OZDKx'
        'i#M}U*n?S_<FT?llSS8(?=bk42xEC(rts@6cXoTYJ#33^U~V%^g=GBN?|An*H&zs>(CPR=U*McvbP++F2E)5rBq5BD+?#`UoZ;TN'
        'ytHs><<jM)D_1VBEMHn#S-!fmxcJ_}(&EbHrIn@S#Vc1YEiWxC_+YD!k)SCfld?#?JH^v7@ooac!krl_2#@=1r9bzyMCT1cOl75I'
        'B7hqI*uBhm)t*dwRcgys>bKl$+?2IWBqlP+D}eyqba-SchV$FN-rjZ?eTsxl{s6YA3`m+vks95{;=DwtrS@)i@Wvk)PuJaaERy>&'
        'xO+O(hUd~4(FJJSx2rnNRKfwqIt!kS@POH=76#ruXB5l@C?In~FnIS$3x{YiT8P5I-iBJ7;Uo<F*RrsDfNlSnmg$OnwMj|Kqyp0|'
        'Y@cOjYJfWF-fYssZOL_6+U77*2^>#9o~IA!8m-cGx`E#st<z1q)%bIY#~FfodkD-CK;WG{{O#RK*OmRS`M!hC0Yu&NysW%qCmmw?'
        'd0Zls2!B)NC14+Xzg<ZLfr^YNL_!J-q<ij_ZIPy`=pI=_GR$t(8G`N~p2Z10k=4@w*3Wm?6B9!xs`en?nW<xho2w#l2rptUyi5lk'
        'p}g4LnF-q_o)|Dg?p2~_G-a!fP2Ax6^``tVpi*V~9JW;nXP4c>HB2xg@+y;tm9Z77kSP<ES(Qt6*D%zZH5*5RnyKCQ**u;XvEl;z'
        '5j*bq+4a3jX&ja|CaA2ll*N*z$|NAPOryZLeT9J>ocRcTcVT~{u(B)l0WG1oJB;3;@6)?qG$GANt-*w(tP2|=`Ta(bXqf|jFj*Ff'
        'WN?F(Nm6Sd7Bb9sBudI`$v%_1WDiId%#viSJTqn3`qr)0TkC7l>|G4YJqQU)<*ov5kxf?aVh?fvfiM=*12JHtV2vALw+cB7_8W*?'
        'geriV_&gNmNR8h*q{dd}4JgoCo-N4qy(4L%i?r}fH1EF5dVp47GSrUVgR(uL$A+#xruVn#hbM55enJ~=Zp>#-oxn@lYBYgvpC|zb'
        'HjPw(KK>fE)6eJ^O~Aw{-ltP{|LuM|Sq#}jRUi$0isWeg%os(eH{!*&+T!yAVJy3U2LOzXh1w6H0zxv`7CM^UXvVQ1uq3ZDtAK&S'
        '%fKr=njAm2(q#-31)#Q$ygM7rfHZZ}#Eym4ZeS=(7fi6A?HcQQDi9vNV8d>>3b0)C1KIMj2Rf(%s0Rln)Ehfk=mQNb&$yWz0nVbZ'
        'Bch$7hx^!?8K>OY&DEds?T@a1xN&3k?#AsczP-M)aeFOfZ06@}=LAFx_no1dLW(qcQn+D^-xOwcnpi|Ov`Gb!JGt0kGE_ze5YE#B'
        'I!nK#KK+p%(Vywd`fCyCo=3C8O{lqhp=k~~ROsm;wV|ywH!w7{#Zg;p;Oh2PSy$qQr;?!@m}V_9w_EDGy(B>vklsUT)-+l}t!APi'
        '<pb8F7?%ZBlr{{YLYBlpY$};3R48T5MKkg(PoC-f)Zq4bB1^vdUsw{4HKI3A_;6_{j_qjf#kQeAIzumi#%cd-jsEMTl?muLd613`'
        '3y;uNny}~^7F`=H8dCYt@E_X6_b__z=;DLJE!}AjdirY6(Rm=N4^(~mO^`-k(O>AV^f&tZNbmmff2|{0yWB%*tl#|4q&tfnX8Ui6'
        '<|IXmM|-h<c%TJb=u8Iwv}8RN2;*fsBADaYcymV-UAcn}X4Ogeo%`)I<by-vJM*N;^{1T)(s2H$^0rk24mQs{cf2k~{{@zU4U4r6'
        '000'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
