# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/dmitry/monitor/monitor_ws/monitor/backend/dsdl_messages/public_regulated_data_types/reg/udral/physics/dynamics/rotation/Planar.0.1.dsdl
#
# Generated at:  2025-11-14 17:37:06.056057 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.dynamics.rotation.Planar
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import reg.udral.physics.kinematics.rotation
import uavcan.si.unit.torque

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Planar_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 kinematics: None | reg.udral.physics.kinematics.rotation.Planar_0_1 = None,
                 torque:     None | uavcan.si.unit.torque.Scalar_1_0 = None) -> None:
        """
        reg.udral.physics.dynamics.rotation.Planar.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param kinematics: reg.udral.physics.kinematics.rotation.Planar.0.1 kinematics
        :param torque:     uavcan.si.unit.torque.Scalar.1.0 torque
        """
        self._kinematics: reg.udral.physics.kinematics.rotation.Planar_0_1
        self._torque:     uavcan.si.unit.torque.Scalar_1_0

        if kinematics is None:
            self.kinematics = reg.udral.physics.kinematics.rotation.Planar_0_1()
        elif isinstance(kinematics, reg.udral.physics.kinematics.rotation.Planar_0_1):
            self.kinematics = kinematics
        else:
            raise ValueError(f'kinematics: expected reg.udral.physics.kinematics.rotation.Planar_0_1 '
                             f'got {type(kinematics).__name__}')

        if torque is None:
            self.torque = uavcan.si.unit.torque.Scalar_1_0()
        elif isinstance(torque, uavcan.si.unit.torque.Scalar_1_0):
            self.torque = torque
        else:
            raise ValueError(f'torque: expected uavcan.si.unit.torque.Scalar_1_0 '
                             f'got {type(torque).__name__}')

    @property
    def kinematics(self) -> reg.udral.physics.kinematics.rotation.Planar_0_1:
        """
        reg.udral.physics.kinematics.rotation.Planar.0.1 kinematics
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._kinematics

    @kinematics.setter
    def kinematics(self, x: reg.udral.physics.kinematics.rotation.Planar_0_1) -> None:
        if isinstance(x, reg.udral.physics.kinematics.rotation.Planar_0_1):
            self._kinematics = x
        else:
            raise ValueError(f'kinematics: expected reg.udral.physics.kinematics.rotation.Planar_0_1 got {type(x).__name__}')

    @property
    def torque(self) -> uavcan.si.unit.torque.Scalar_1_0:
        """
        uavcan.si.unit.torque.Scalar.1.0 torque
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._torque

    @torque.setter
    def torque(self, x: uavcan.si.unit.torque.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.torque.Scalar_1_0):
            self._torque = x
        else:
            raise ValueError(f'torque: expected uavcan.si.unit.torque.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.kinematics._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.torque._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 128 <= (_ser_.current_bit_length - _base_offset_) <= 128, \
            'Bad serialization of reg.udral.physics.dynamics.rotation.Planar.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Planar_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "kinematics"
        _des_.pad_to_alignment(8)
        _f0_ = reg.udral.physics.kinematics.rotation.Planar_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "torque"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.torque.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Planar_0_1(
            kinematics=_f0_,
            torque=_f1_)
        _des_.pad_to_alignment(8)
        assert 128 <= (_des_.consumed_bit_length - _base_offset_) <= 128, \
            'Bad deserialization of reg.udral.physics.dynamics.rotation.Planar.0.1'
        assert isinstance(self, Planar_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'kinematics=%s' % self.kinematics,
            'torque=%s' % self.torque,
        ])
        return f'reg.udral.physics.dynamics.rotation.Planar.0.1({_o_0_})'

    _EXTENT_BYTES_ = 16

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8!e|$10{_KV-EUMy6mO+$p&%atB>@s|h`~bi_G=4^QG+1$V_{vvn3!mWx%W<crre#m+?l)Wl8}IjhQ>)WVN86~N8gP9fR6@^'
        '{s+F9_($l2XYSqGZM)sJng~s{ojvEw`TU(Tr}sv_`uxC9{$rj?I+2QEpD31c8uL3eh?!49*-E71npyMo4V`A8&QkV%Ct>!XJ#*jQ'
        'wc}<t5wwN;vngBfvnZvppFl_PQ29{@S?-WZO*NOoZ^l&6)S5k{%~FLF3qxk~gYNmEtq;|QKeP9(*+;0>DGxHul>HdZ3~+E&%9`DC'
        'oW)Vku`v=+O^J5i!czqicAFRb{k+8mYoUXicnYJiw{!~jqa$#rtLexZohLHd4yo`J_cOt@PsIW{cO#^6sbaW3RI2D{7!*{J@)p;;'
        'jX~|5izU_TGro@mT$7lI1r4_DVW1&ZnzUqufj)1ZZI;*FHUBd5t~r*=?x*&;HAjikR75n5)+%~{dRlY=-OnOtcs`|}%Y?#e&2`VH'
        '!@Mw4ot&;s&s5Kyo2kuC*J`sDYEx6^C#zGnnQE;%J9X~D^lY^{X`QVs!0c2~8gVMD86lAjtr<cxHAmJ|m;{{yMRzTnhf@kej98Mg'
        'kZKm$6?1^h^JNy1M5dbX$TrMjqGXna3>h&a3B>@+sQVN10G)3lXqTIg`VbQ~Jb|`BI+Ru-OikKB;g-ZuC1P=`dm>B9!WA<b(C`)$'
        '5hC8zhP0ScbOBLlP9#|n^N=8bve<dn0~m5E1qQ5nN^vyjaDbT1kzmci0t^0>Kj}NIR=YwRAwU&6pE98x1ll}gb_Hs1!5qr-QS_fc'
        'cF_b|+NgB##>}xiAw)}(N~v>ADxs(wULS``a2ei!D=>$jH{mUK8{WyC86iQ8VVo`@*@FhUrZ;}KX8$Fwujb!x;MXoV%`PGnYrH{9'
        'RHqe4%pt~pjkP2K-ofhKgr(HgVin>Q5(39&hR_^r(kS9$p-%|FaT{5TL3cKCQA3-?8M9y5@w)e=3UK5kg(6$ulLZ)ViwoC1c%aMf'
        'FzPx83+rx=5w@IAkx!*Y7N{Tx@*&JL3Zx{TiTU)xS|Mw*nQ*#)CggY9ES4eHo$bd1obH~^)IB&0K1@7-NtpQ$9eB9tK!QoaI)oC@'
        'U3gC6Wo)?>_(Z`gEAVOqUK;=rsKeD>{ACOl8V)<~UJhEgJ`kh*H+yh}54V6Nd;}!V0tCQT>%O>p5(V>iS!PhKx}Y&*8GhQxTi&FA'
        'y#NLm@a%vB(lBJPLz{ah9%B(t_7!nZJ->(Vc2v)!n}xLFnr?pkiPUvKAbCodOUXEN;5d8(ci<=ZHrp~cW*5$PoT~YX;2xD?Nx+%V'
        'TNCg}EEffw?Zv8qlYOc;+w=69W7oS<9t~usJ&K2Au6$dh_1{{mbeEEWseQDQ)Uq|>^O?(1xJOoOI)}~PVhrQ^<er~xwEa;S{d17y'
        '{D2z5*GxI;MWkNrQA^<s<R1&+n@GLcFT9@IMaSB7Zqe^2H}pFu;&#R!XNT_>Y)MOjD~D$3+Kyh_H#{`7ID)@+)Yp~5^&NL|DgQ)z'
        'ch%XNInbaDkI#FVxFzJ0u&d4c7aU$Zh0(*`TlX$Jf}i0Rv#0#W!@{rdTdy5|Xy)&Bn|Xyzk1H>fFGU<TO<d=^C9c6sN}2MJpC})T'
        'iFK2IteMI-kMJ69)40QWE!y#D9Lpt714F$+Wi6JXDG!CR5J@c6lnW1d6fsd=Q&|WeRr#eB?x;e0a^6G4rkd03CPgpO|8q`k*V(@h'
        '=)c9|ShJ#E?;+z}f4{CLJ4E>Z0Lt9(J(dmt00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
